# Spider Error Analysis

Notebook for analyzing the current best full Spider dev run:
- global metrics and cost
- top problematic databases
- natural-language questions from problematic databases
- clearly wrong predictions outside those databases

Current target run:
`outputs/ablation_cheap_gen_more_candidates_20260407_204301_20260407_204302.json`

In [1]:
from __future__ import annotations

import json
from collections import Counter
from pathlib import Path
from pprint import pprint

RUN_PATH = Path('../outputs/ablation_cheap_gen_more_candidates_20260407_204301_20260407_204302.json')
assert RUN_PATH.exists(), RUN_PATH

payload = json.loads(RUN_PATH.read_text())
predictions = payload['predictions']
metrics = payload['metrics']
timings = payload['timings']
cost = payload['cost']

print('Run file:', RUN_PATH)
print('EX:', round(metrics['execution_accuracy'] * 100, 2), '%')
print('EM:', round(metrics['exact_match'] * 100, 2), '%')
print('Errors:', metrics['errors'])
print('Avg time/example:', timings['avg_time_per_example_s'])
print('Total cost USD:', round(cost['total_cost_usd'], 4))
print('Avg cost/example USD:', round(cost['avg_cost_per_example_usd'], 5))
print('Total predictions:', len(predictions))

Run file: ../outputs/ablation_cheap_gen_more_candidates_20260407_204301_20260407_204302.json
EX: 72.34 %
EM: 33.66 %
Errors: 28
Avg time/example: 3.5758
Total cost USD: 21.9847
Avg cost/example USD: 0.02126
Total predictions: 1034

In [2]:
# Top problematic databases by hard errors
error_db = Counter()
for row in predictions:
    if row.get('error_message'):
        error_db[row['db_id']] += 1

top_problem_dbs = [db for db, _ in error_db.most_common(8)]
print('Top problematic DBs:')
for db, n in error_db.most_common(12):
    print(f'{db:30s} {n}')

top_problem_dbs

Top problematic DBs:
dog_kennels                    9
car_1                          5
student_transcripts_tracking   4
concert_singer                 2
flight_2                       2
employee_hire_evaluation       2
wta_1                          2
world_1                        2

['dog_kennels',
 'car_1',
 'student_transcripts_tracking',
 'concert_singer',
 'flight_2',
 'employee_hire_evaluation',
 'wta_1',
 'world_1']

In [3]:
# Natural-language questions from the main problematic DBs
focus_dbs = ['dog_kennels', 'car_1', 'student_transcripts_tracking']
focus_questions = {db: [] for db in focus_dbs}

for row in predictions:
    db = row['db_id']
    if db in focus_questions and row['question'] not in focus_questions[db]:
        focus_questions[db].append(row['question'])

for db in focus_dbs:
    print('\n' + '=' * 80)
    print(db)
    print('=' * 80)
    for i, question in enumerate(focus_questions[db], 1):
        print(f'{i:2d}. {question}')

================================================================================
dog_kennels
================================================================================
 1. Which states have both owners and professionals living there?
 2. Find the states where both owners and professionals live.
 3. What is the average age of the dogs who have gone through any treatments?
 4. Find the average age of the dogs who went through treatments.
 5. Which professionals live in the state of Indiana or have done treatment on more than 2 treatments? List his or her id, last name and cell phone.
 6. Find the id, last name and cell phone of the professionals who live in the state of Indiana or have performed more than two treatments.
 7. Which dogs have not cost their owner more than 1000 for treatment? List the dog names.
 8. What are the names of the dogs for which the owner spent more than 1000 for treatment?
 9. Which first names are used for professionals or owners but are not used as dog names?
10. Find the first names that are used for professionals or owners but are not used as dog names.
11. Which professional did not operate any treatment on dogs? List the professional's id, role and email.
12. Give me the id, role and email of the professionals who did not perform any treatment on dogs.
13. Which owner owns the most dogs? List the owner id, first name and last name.
14. Return the owner id, first name and last name of the owner who has the most dogs.
15. Which professionals have done at least two treatments? List the professional's id, role, and first name.
16. What are the id, role, and first name of the professionals who have performed two or more treatments?
17. What is the name of the breed with the most dogs?
18. Which breed do the most dogs have? Give me the breed name.
19. Which owner has paid for the most treatments on his or her dogs? List the owner id and last name.
20. Tell me the owner id and last name of the owner who spent the most on treatments of his or her dogs.
21. What is the description of the treatment type that costs the least money in total?
22. Give me the description of the treatment type whose total cost is the lowest.
23. Which owner has paid the largest amount of money in total for their dogs? Show the owner id and zip code.
24. Find the owner id and zip code of the owner who spent the most money in total for his or her dogs.
25. Which professionals have done at least two types of treatments? List the professional id and cell phone.
26. Find the id and cell phone of the professionals who operate two or more types of treatments.
27. What are the first name and last name of the professionals who have done treatment with cost below average?
28. Which professionals have operated a treatment that costs less than the average? Give me theor first names and last names.
29. List the date of each treatment, together with the first name of the professional who operated it.
30. What are the date and the operating professional's first name of each treatment?
31. List the cost of each treatment and the corresponding treatment type description.
32. What are the cost and treatment type description of each treatment?
33. List each owner's first name, last name, and the size of his for her dog.
34. What are each owner's first name, last name, and the size of their dog?
35. List pairs of the owner's first name and the dogs's name.
36. What are each owner's first name and their dogs's name?
37. List the names of the dogs of the rarest breed and the treatment dates of them.
38. Which dogs are of the rarest breed? Show their names and treatment dates.
39. Which dogs are owned by someone who lives in Virginia? List the owner's first name and the dog's name.
40. Find the first names of owners living in Virginia and the names of dogs they own.
41. What are the arriving date and the departing date of the dogs who have gone through a treatment?
42. Find the arriving date and the departing date of the dogs that received a treatment.
43. List the last name of the owner owning the youngest dog.
44. Who owns the youngest dog? Give me his or her last name.
45. List the emails of the professionals who live in the state of Hawaii or the state of Wisconsin.
46. What are the emails of the professionals living in either the state of Hawaii or the state of Wisconsin?
47. What are the arriving date and the departing date of all the dogs?
48. List the arrival date and the departure date for all the dogs.
49. How many dogs went through any treatments?
50. Count the number of dogs that went through a treatment.
51. How many professionals have performed any treatment to dogs?
52. Find the number of professionals who have ever treated dogs.
53. Which professionals live in a city containing the substring 'West'? List his or her role, street, city and state.
54. Find the role, street, city and state of the professionals living in a city that contains the substring 'West'.
55. Which owners live in the state whose name contains the substring 'North'? List his first name, last name and email.
56. Return the first name, last name and email of the owners living in a state whose name contains the substring 'North'.
57. How many dogs have an age below the average?
58. Count the number of dogs of an age below the average.
59. How much does the most recent treatment cost?
60. Show me the cost of the most recently performed treatment.
61. How many dogs have not gone through any treatment?
62. Tell me the number of dogs that have received any treatment.
63. How many owners temporarily do not have any dogs?
64. Find the number of owners who do not own any dogs at this moment.
65. How many professionals did not operate any treatment on dogs?
66. Find the number of professionals who have not treated any dogs.
67. List the dog name, age and weight of the dogs who have been abandoned? 1 stands for yes, and 0 stands for no.
68. What are the dog name, age and weight of the dogs that were abandoned? Note that 1 stands for yes, and 0 stands for no in the tables.
69. What is the average age of all the dogs?
70. Compute the average age of all the dogs.
71. What is the age of the oldest dog?
72. Tell me the age of the oldest dog.
73. How much does each charge type costs? List both charge type and amount.
74. List each charge type and its amount.
75. How much does the most expensive charge type costs?
76. What is the charge amount of the most expensive charge type?
77. List the email, cell phone and home phone of all the professionals.
78. What are the email, cell phone and home phone of each professional?
79. What are all the possible breed type and size type combinations?
80. Find the distinct breed type and size type combinations for dogs.
81. List the first name of all the professionals along with the description of the treatment they have done.
82. What are each professional's first name and description of the treatment they have performed?

================================================================================
car_1
================================================================================
 1. How many continents are there?
 2. What is the number of continents?
 3. How many countries does each continent have? List the continent id, continent name and the number of countries.
 4. For each continent, list its id, name, and how many countries it has?
 5. How many countries are listed?
 6. How many countries exist?
 7. How many models does each car maker produce? List maker full name, id and the number.
 8. What is the full name of each car maker, along with its id and how many models it produces?
 9. Which model of the car has the minimum horsepower?
10. What is the model of the car with the smallest amount of horsepower?
11. Find the model of the car whose weight is below the average weight.
12. What is the model for the car with a weight smaller than the average?
13. Find the name of the makers that produced some cars in the year of 1970?
14. What is the name of the different car makers who produced a car in 1970?
15. Find the make and production time of the cars that were produced in the earliest year?
16. What is the maker of the carr produced in the earliest year and what year was it?
17. Which distinct car models are the produced after 1980?
18. What are the different models for the cards produced after 1980?
19. How many car makers are there in each continents? List the continent name and the count.
20. What is the name of each continent and how many car makers are there in each one?
21. Which of the countries has the most car makers? List the country name.
22. What is the name of the country with the most car makers?
23. How many car models are produced by each maker? List the count and the maker full name.
24. What is the number of car models that are produced by each maker and what is the id and full name of each maker?
25. What is the accelerate of the car make amc hornet sportabout (sw)?
26. How much does the car accelerate that makes amc hornet sportabout (sw)?
27. How many car makers are there in france?
28. What is the number of makers of care in France?
29. How many car models are produced in the usa?
30. What is the count of the car models produced in the United States?
31. What is the average miles per gallon(mpg) of the cars with 4 cylinders?
32. What is the average miles per gallon of all the cards with 4 cylinders?
33. What is the smallest weight of the car produced with 8 cylinders on 1974?
34. What is the minimu weight of the car with 8 cylinders produced in 1974?
35. What are all the makers and models?
36. What are the makers and models?
37. What are the countries having at least one car maker? List name and id.
38. What are the names and ids of all countries with at least one car maker?
39. What is the number of the cars with horsepower more than 150?
40. What is the number of cars with a horsepower greater than 150?
41. What is the average weight of cars each year?
42. What is the average weight and year for each year?
43. Which countries in europe have at least 3 car manufacturers?
44. What are the names of all European countries with at least 3 manufacturers?
45. What is the maximum horsepower and the make of the car models with 3 cylinders?
46. What is the largest amount of horsepower for the models with 3 cylinders and what make is it?
47. Which model saves the most gasoline? That is to say, have the maximum miles per gallon.
48. What is the car wmodel with the highest mpg?
49. What is the average horsepower of the cars before 1980?
50. What is the average horsepower for all cards produced before 1980?
51. What is the average edispl of the cars of model volvo?
52. What is the average edispl for all volvos?
53. What is the maximum accelerate for different number of cylinders?
54. What is the maximum accelerate for all the different cylinders?
55. Which model has the most version(make) of cars?
56. What model has the most different versions?
57. How many cars have more than 4 cylinders?
58. What is the number of cars with more than 4 cylinders?
59. how many cars were produced in 1980?
60. In 1980, how many cars were made?
61. How many car models were produced by the maker with full name American Motor Company?
62. What is the number of car models created by the car maker American Motor Company?
63. Which makers designed more than 3 car models? List full name and the id.
64. What are the names and ids of all makers with more than 3 models?
65. Which distinctive models are produced by maker with the full name General Motors or weighing more than 3500?
66. What are the different models created by either the car maker General Motors or weighed more than 3500?
67. In which years cars were produced weighing no less than 3000 and no more than 4000?
68. What are the different years in which there were cars produced that weighed less than 4000 and also cars that weighted more than 3000?
69. What is the horsepower of the car with the largest accelerate?
70. What is the horsepower of the car with the greatest accelerate?
71. For model volvo, how many cylinders does the car with the least accelerate have?
72. For a volvo model, how many cylinders does the version with least accelerate have?
73. How many cars have a larger accelerate than the car with the largest horsepower?
74. What is the number of cars with a greater accelerate than the one with the most horsepower?
75. How many countries has more than 2 car makers?
76. What is the number of countries with more than 2 car makers?
77. How many cars has over 6 cylinders?
78. What is the number of carsw ith over 6 cylinders?
79. For the cars with 4 cylinders, which model has the largest horsepower?
80. For all of the 4 cylinder cars, which model has the most horsepower?
81. Among the cars with more than lowest horsepower, which ones do not have more than 3 cylinders? List the car makeid and make name.
82. Among the cars that do not have the minimum horsepower, what are the make ids and names of al those with less than 4 cylinders?
83. What is the maximum miles per gallon of the car with 8 cylinders or produced before 1980?
84. What is the maximum mpg of the cars that had 8 cylinders or that were produced before 1980?
85. Which models are lighter than 3500 but not built by the 'Ford Motor Company'?
86. What are the different models wthat are lighter than 3500 but were not built by the Ford Motor Company?
87. What are the name of the countries where there is not a single car maker?
88. What are the names of the countries with no car makers?
89. Which are the car makers which produce at least 2 models and more than 3 car makes? List the id and the maker.
90. What are the ids and makers of all car makers that produce at least 2 models and make more than 3 cars?
91. What are the id and names of the countries which have more than 3 car makers or produce the 'fiat' model?
92. What are the ids and names of all countries that either have more than 3 car makers or produce fiats?

================================================================================
student_transcripts_tracking
================================================================================
 1. what are all the addresses including line 1 and line 2?
 2. What is the first and second line for all addresses?
 3. How many courses in total are listed?
 4. How many courses are there?
 5. How is the math course described?
 6. What are the descriptions for all the math courses?
 7. What is the zip code of the address in the city Port Chelsea?
 8. What is the zip code for Port Chelsea?
 9. Which department offers the most number of degrees? List department name and id.
10. For each department id, what is the name of the department with the most number of degrees?
11. How many departments offer any degree?
12. How many different departments offer degrees?
13. How many different degree names are offered?
14. How many different degrees are offered?
15. How many degrees does the engineering department offer?
16. How many degrees does the engineering department have?
17. What are the names and descriptions of all the sections?
18. What are the names and descriptions for all the sections?
19. What are the names and id of courses having at most 2 sections?
20. What are the names and ids of every course with less than 2 sections?
21. List the section_name in reversed lexicographical order.
22. What are the names of the sections in reverse alphabetical order?
23. What is the semester which most student registered in? Show both the name and the id.
24. For each semester, what is the name and id of the one with the most students registered?
25. What is the description of the department whose name has the substring the computer?
26. What is the department description for the one whose name has the word computer?
27. Who are enrolled in 2 degree programs in one semester? List the first name, middle name and last name and the id.
28. What are the first, middle, and last names, along with the ids, of all students who enrolled in 2 degree programs in one semester?
29. Who is enrolled in a Bachelor degree program? List the first name, middle name, last name.
30. What are the first, middle, and last names for everybody enrolled in a Bachelors program?
31. Find the kind of program which most number of students are enrolled in?
32. What is the degree summary name that has the most number of students enrolled?
33. Find the program which most number of students are enrolled in. List both the id and the summary.
34. What is the program id and the summary of the degree that has the most students enrolled?
35. Which student has enrolled for the most times in any program? List the id, first name, middle name, last name, the number of enrollments and student id.
36. What is the first, middle, and last name, along with the id and number of enrollments, for the student who enrolled the most in any program?
37. Which semesters do not have any student enrolled? List the semester name.
38. What is the name of the semester with no students enrolled?
39. What are all the course names of the courses which ever have students enrolled in?
40. What are the names of all courses that have some students enrolled?
41. What's the name of the course with most number of enrollments?
42. What is the name of the course with the most students enrolled?
43. Find the last name of the students who currently live in the state of North Carolina but have not registered in any degree program.
44. What are the last name of the students who live in North Carolina but have not registered in any degree programs?
45. Show the date and id of the transcript with at least 2 course results.
46. What is the date and id of the transcript with at least 2 courses listed?
47. What is the phone number of the man with the first name Timmothy and the last name Ward?
48. What is the mobile phone number of the student named Timothy Ward?
49. Who is the first student to register? List the first name, middle name and last name.
50. What is the first, middle, and last name of the first student to register?
51. Who is the earliest graduate of the school? List the first name, middle name and last name.
52. What is the first, middle, and last name of the earliest school graduate?
53. Whose permanent address is different from his or her current address? List his or her first name.
54. What is the first name of the student whose permanent address is different from his or her current one?
55. Which address holds the most number of students currently? List the address id and all lines.
56. What is the id, line 1, and line 2 of the address with the most students?
57. On average, when were the transcripts printed?
58. What is the average transcript date?
59. When is the first transcript released? List the date and details.
60. What is the earliest date of a transcript release, and what details can you tell me?
61. How many transcripts are released?
62. How many transcripts are listed?
63. What is the last transcript release date?
64. When was the last transcript released?
65. How many times at most can a course enrollment result show in different transcripts? Also show the course enrollment id.
66. What is the maximum number of times that a course shows up in different transcripts and what is that course's enrollment id?
67. Show the date of the transcript which shows the least number of results, also list the id.
68. What is the date and id of the transcript with the least number of results?
69. Find the semester when both Master students and Bachelor students got enrolled in.
70. What is the id of the semester that had both Masters and Bachelors students enrolled?
71. How many different addresses do the students currently live?
72. What are the different addresses that have students living there?
73. List all the student details in reversed lexicographical order.
74. What other details can you tell me about students in reverse alphabetical order?
75. Describe the section h.

In [9]:
# dog_kennels: the 9 hard-error rows in full detail

dog_rows = [
    row for row in predictions
    if row['db_id'] == 'dog_kennels' and row.get('error_message')
]

print('dog_kennels hard-error rows:', len(dog_rows))
for i, row in enumerate(dog_rows, 1):
    print('\n' + '=' * 120)
    print(f'[{i}] QUESTION: {row["question"]}')
    print(f'PREDICTED SQL: {row["predicted_sql"]}')
    print(f'GOLD SQL:      {row["gold_sql"]}')
    print(f'EXEC MATCH:    {row["execution_match"]}')
    print(f'ERROR:         {row.get("error_message")}')
    print('WARNINGS:')
    for w in row.get('warnings', []):
        print('  -', w)

dog_kennels hard-error rows: 9

========================================================================================================================
[1] QUESTION: What are the names of the dogs for which the owner spent more than 1000 for treatment?
PREDICTED SQL: SELECT name FROM Dogs WHERE dog_id IN (SELECT dog_id FROM Treatments GROUP BY dog_id HAVING SUM(cost) > 1000);
GOLD SQL:      SELECT name FROM Dogs WHERE dog_id NOT IN( SELECT dog_id FROM Treatments GROUP BY dog_id HAVING sum(cost_of_treatment)  >  1000 )
EXEC MATCH:    False
ERROR:         (sqlite3.OperationalError) no such column: amount
[SQL: SELECT name FROM Dogs WHERE dog_id IN (SELECT dog_id FROM Treatments GROUP BY dog_id HAVING SUM(amount) > 1000);]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
WARNINGS:
  - query_sketcher: failed to parse JSON response
  - query_sketcher: repaired malformed sketch with structured-output fallback
  - generator: using reduced ensemble budget for moderate complexity
  - execution_filter: (sqlite3.OperationalError) no such column: T2.cost
[SQL: SELECT T1.name FROM Dogs AS T1 JOIN Treatments AS T2 ON T1.dog_id = T2.dog_id GROUP BY T1.dog_id HAVING SUM(T2.cost) > 1000;]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
  - execution_filter: (sqlite3.OperationalError) no such column: T2.cost
[SQL: SELECT T1.name FROM Dogs AS T1 JOIN Treatments AS T2 ON T1.dog_id = T2.dog_id GROUP BY T1.dog_id HAVING SUM(T2.cost) > 1000;]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
  - execution_filter: 2/2 candidates failed
  - execution_filter: no valid candidates after execution
  - schema_validation: unknown column 'T2.cost'

========================================================================================================================
[2] QUESTION: Tell me the owner id and last name of the owner who spent the most on treatments of his or her dogs.
PREDICTED SQL: SELECT O.owner_id, O.last_name FROM Owners O JOIN Dogs D ON O.owner_id = D.owner_id JOIN Treatments T ON D.dog_id = T.dog_id GROUP BY O.owner_id ORDER BY SUM(T.cost) DESC LIMIT 1;
GOLD SQL:      SELECT T1.owner_id ,  T1.last_name FROM Owners AS T1 JOIN Dogs AS T2 ON T1.owner_id  =  T2.owner_id JOIN Treatments AS T3 ON T2.dog_id  =  T3.dog_id GROUP BY T1.owner_id ORDER BY count(*) DESC LIMIT 1
EXEC MATCH:    False
ERROR:         schema_validation: unknown column 'T.treatment_cost'
WARNINGS:
  - query_sketcher: failed to parse JSON response
  - query_sketcher: structured repair unavailable (Could not parse response content as the length limit was reached - CompletionUsage(completion_tokens=2020, prompt_tokens=1375, total_tokens=3395, completion_tokens_details=CompletionTokensDetails(accepted_prediction_tokens=None, audio_tokens=0, reasoning_tokens=1969, rejected_prediction_tokens=None, image_tokens=0), prompt_tokens_details=PromptTokensDetails(audio_tokens=0, cached_tokens=0, cache_write_tokens=0, video_tokens=0), cost=0.02191875, is_byok=False, cost_details={'upstream_inference_cost': 0.02191875, 'upstream_inference_prompt_cost': 0.00171875, 'upstream_inference_completions_cost': 0.0202}))
  - query_sketcher: used deterministic fallback sketch
  - generator: using reduced ensemble budget for moderate complexity
  - execution_filter: (sqlite3.OperationalError) no such column: T3.amount
[SQL: SELECT T1.owner_id, T1.last_name FROM Owners AS T1 JOIN Dogs AS T2 ON T1.owner_id = T2.owner_id JOIN Treatments AS T3 ON T2.dog_id = T3.dog_id GROUP BY T1.owner_id ORDER BY SUM(T3.amount) DESC LIMIT 1;]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
  - execution_filter: (sqlite3.OperationalError) no such column: T3.amount
[SQL: SELECT T1.owner_id, T1.last_name FROM Owners AS T1 JOIN Dogs AS T2 ON T1.owner_id = T2.owner_id JOIN Treatments AS T3 ON T2.dog_id = T3.dog_id GROUP BY T1.owner_id ORDER BY SUM(T3.amount) DESC LIMIT 1;]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
  - execution_filter: 2/2 candidates failed
  - execution_filter: no valid candidates after execution
  - schema_validation: unknown column 'T3.amount'
  - schema_validation: unknown column 'T.cost'
  - schema_validation: unknown column 'T.treatment_cost'

========================================================================================================================
[3] QUESTION: Give me the description of the treatment type whose total cost is the lowest.
PREDICTED SQL: SELECT T2.treatment_type_description FROM Treatments AS T1 JOIN Treatment_Types AS T2 ON T1.treatment_type_code = T2.treatment_type_code GROUP BY T2.treatment_type_description ORDER BY SUM(T1.treatment_cost) ASC LIMIT 1;
GOLD SQL:      SELECT T1.treatment_type_description FROM Treatment_types AS T1 JOIN Treatments AS T2 ON T1.treatment_type_code  =  T2.treatment_type_code GROUP BY T1.treatment_type_code ORDER BY sum(cost_of_treatment) ASC LIMIT 1
EXEC MATCH:    False
ERROR:         schema_validation: unknown column 'T1.treatment_cost'
WARNINGS:
  - generator: using reduced ensemble budget for moderate complexity
  - execution_filter: (sqlite3.OperationalError) no such column: T1.cost
[SQL: SELECT T2.treatment_type_description FROM Treatments AS T1 JOIN Treatment_Types AS T2 ON T1.treatment_type_code = T2.treatment_type_code GROUP BY T2.treatment_type_description ORDER BY SUM(T1.cost) ASC LIMIT 1;]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
  - execution_filter: (sqlite3.OperationalError) no such column: T1.cost
[SQL: SELECT T2.treatment_type_description FROM Treatments AS T1 JOIN Treatment_Types AS T2 ON T1.treatment_type_code = T2.treatment_type_code GROUP BY T2.treatment_type_description ORDER BY SUM(T1.cost) ASC LIMIT 1;]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
  - execution_filter: 2/2 candidates failed
  - execution_filter: no valid candidates after execution
  - schema_validation: unknown column 'T1.cost'
  - schema_validation: unknown column 'T1.treatment_cost'
  - schema_validation: unknown column 'T1.treatment_cost'

========================================================================================================================
[4] QUESTION: Find the id and cell phone of the professionals who operate two or more types of treatments.
PREDICTED SQL: SELECT p.professional_id, p.cell_number FROM Professionals p JOIN Treatments t ON p.professional_id = t.professional_id GROUP BY p.professional_id, p.cell_number HAVING COUNT(DISTINCT t.treatment_type_code) >= 2;
GOLD SQL:      SELECT T1.professional_id ,  T1.cell_number FROM Professionals AS T1 JOIN Treatments AS T2 ON T1.professional_id  =  T2.professional_id GROUP BY T1.professional_id HAVING count(*)  >=  2
EXEC MATCH:    False
ERROR:         schema_validation: unknown column 't.treatment_code'
WARNINGS:
  - query_sketcher: failed to parse JSON response
  - query_sketcher: structured repair unavailable (Could not parse response content as the length limit was reached - CompletionUsage(completion_tokens=2032, prompt_tokens=537, total_tokens=2569, completion_tokens_details=CompletionTokensDetails(accepted_prediction_tokens=None, audio_tokens=0, reasoning_tokens=1944, rejected_prediction_tokens=None, image_tokens=0), prompt_tokens_details=PromptTokensDetails(audio_tokens=0, cached_tokens=0, cache_write_tokens=0, video_tokens=0), cost=0.02099125, is_byok=False, cost_details={'upstream_inference_cost': 0.02099125, 'upstream_inference_prompt_cost': 0.00067125, 'upstream_inference_completions_cost': 0.02032}))
  - query_sketcher: used deterministic fallback sketch
  - generator: using reduced ensemble budget for moderate complexity
  - execution_filter: (sqlite3.OperationalError) no such column: treatment_type
[SQL: SELECT professional_id, cell_number FROM Professionals GROUP BY professional_id HAVING COUNT(DISTINCT treatment_type) >= 2;]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
  - execution_filter: (sqlite3.OperationalError) no such column: treatment_type
[SQL: SELECT professional_id , cell_number FROM Professionals GROUP BY professional_id HAVING count(DISTINCT treatment_type) >= 2;]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
  - execution_filter: 2/2 candidates failed
  - execution_filter: no valid candidates after execution
  - schema_validation_warning: unknown unqualified column 'treatment_type'
  - schema_validation: unknown column 't.treatment_type'
  - schema_validation: unknown column 't.treatment_code'

========================================================================================================================
[5] QUESTION: Which professionals have operated a treatment that costs less than the average? Give me theor first names and last names.
PREDICTED SQL: SELECT DISTINCT P.first_name, P.last_name FROM Professionals P JOIN Treatments T ON P.professional_id = T.professional_id WHERE T.cost < (SELECT AVG(cost) FROM Treatments);
GOLD SQL:      SELECT DISTINCT T1.first_name ,  T1.last_name FROM Professionals AS T1 JOIN Treatments AS T2 WHERE cost_of_treatment  <  ( SELECT avg(cost_of_treatment) FROM Treatments )
EXEC MATCH:    False
ERROR:         schema_validation: unknown column 'T.cost'
WARNINGS:
  - query_sketcher: failed to parse JSON response
  - query_sketcher: structured repair unavailable (Could not parse response content as the length limit was reached - CompletionUsage(completion_tokens=2033, prompt_tokens=522, total_tokens=2555, completion_tokens_details=CompletionTokensDetails(accepted_prediction_tokens=None, audio_tokens=0, reasoning_tokens=1740, rejected_prediction_tokens=None, image_tokens=0), prompt_tokens_details=PromptTokensDetails(audio_tokens=0, cached_tokens=0, cache_write_tokens=0, video_tokens=0), cost=0.0209825, is_byok=False, cost_details={'upstream_inference_cost': 0.0209825, 'upstream_inference_prompt_cost': 0.0006525, 'upstream_inference_completions_cost': 0.02033}))
  - query_sketcher: used deterministic fallback sketch
  - generator: using reduced ensemble budget for moderate complexity
  - execution_filter: (sqlite3.OperationalError) no such table: Professional_Treatments
[SQL: SELECT T1.first_name, T1.last_name FROM Professionals AS T1 JOIN Professional_Treatments AS T2 ON T1.professional_id = T2.professional_id JOIN Treatments AS T3 ON T2.treatment_id = T3.treatment_id WHERE T3.cost < (SELECT AVG(cost) FROM Treatments);]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
  - execution_filter: (sqlite3.OperationalError) no such column: T2.cost
[SQL: SELECT T1.first_name, T1.last_name FROM Professionals AS T1 JOIN Treatments AS T2 ON T1.professional_id = T2.professional_id WHERE T2.cost < (SELECT AVG(cost) FROM Treatments);]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
  - execution_filter: 2/2 candidates failed
  - execution_filter: no valid candidates after execution
  - schema_validation_warning: unknown unqualified column 'cost'
  - schema_validation: unknown table 'Professional_Treatments'; unknown table or alias 'T2' for column 'professional_id'; unknown table or alias 'T2' for column 'treatment_id'; unknown column 'T3.cost'
  - schema_validation_warning: unknown unqualified column 'cost'
  - schema_validation: unknown column 'T.cost'
  - schema_validation_warning: unknown unqualified column 'cost'
  - schema_validation: unknown column 'T.cost'

========================================================================================================================
[6] QUESTION: What are the cost and treatment type description of each treatment?
PREDICTED SQL: SELECT T1.treatment_type_code, T2.treatment_type_description FROM Treatments AS T1 JOIN Treatment_Types AS T2 ON T1.treatment_type_code = T2.treatment_type_code;
GOLD SQL:      SELECT T1.cost_of_treatment ,  T2.treatment_type_description FROM Treatments AS T1 JOIN treatment_types AS T2 ON T1.treatment_type_code  =  T2.treatment_type_code
EXEC MATCH:    False
ERROR:         schema_validation: unknown column 'T1.treatment_cost'
WARNINGS:
  - execution_filter: (sqlite3.OperationalError) no such column: T1.cost
[SQL: SELECT T1.cost , T2.treatment_type_description FROM Treatments AS T1 JOIN Treatment_Types AS T2 ON T1.treatment_type_code = T2.treatment_type_code;]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
  - execution_filter: (sqlite3.OperationalError) no such column: T1.cost
[SQL: SELECT T1.cost , T2.treatment_type_description FROM Treatments AS T1 JOIN Treatment_Types AS T2 ON T1.treatment_type_code = T2.treatment_type_code;]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
  - execution_filter: (sqlite3.OperationalError) no such column: T1.cost
[SQL: SELECT T1.cost, T2.treatment_type_description FROM Treatments AS T1 JOIN Treatment_Types AS T2 ON T1.treatment_type_code = T2.treatment_type_code;]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
  - execution_filter: 3/3 candidates failed
  - execution_filter: no valid candidates after execution
  - schema_validation: unknown column 'T1.cost'
  - schema_validation: unknown column 'T1.amount'
  - schema_validation: unknown column 'T1.treatment_cost'

========================================================================================================================
[7] QUESTION: Show me the cost of the most recently performed treatment.
PREDICTED SQL: SELECT treatment_cost FROM Treatments ORDER BY treatment_date DESC LIMIT 1;
GOLD SQL:      SELECT cost_of_treatment FROM Treatments ORDER BY date_of_treatment DESC LIMIT 1
EXEC MATCH:    False
ERROR:         (sqlite3.OperationalError) no such column: cost
[SQL: SELECT cost FROM Treatments ORDER BY treatment_date DESC LIMIT 1;]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
WARNINGS:
  - generator: using reduced ensemble budget for moderate complexity
  - execution_filter: (sqlite3.OperationalError) no such column: cost
[SQL: SELECT cost FROM Treatments ORDER BY treatment_date DESC LIMIT 1;]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
  - execution_filter: (sqlite3.OperationalError) no such column: cost
[SQL: SELECT cost FROM Treatments ORDER BY treatment_date DESC LIMIT 1;]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
  - execution_filter: 2/2 candidates failed
  - execution_filter: no valid candidates after execution
  - schema_validation_warning: unknown unqualified column 'cost'; unknown unqualified column 'treatment_date'
  - schema_validation_warning: unknown unqualified column 'treatment_cost'; unknown unqualified column 'treatment_date'
  - schema_validation_warning: unknown unqualified column 'cost'; unknown unqualified column 'treatment_date'

========================================================================================================================
[8] QUESTION: List the first name of all the professionals along with the description of the treatment they have done.
PREDICTED SQL: SELECT Professionals.first_name, Treatments.description FROM Professionals JOIN Treatments ON Professionals.professional_id = Treatments.professional_id;
GOLD SQL:      SELECT DISTINCT T1.first_name ,  T3.treatment_type_description FROM professionals AS T1 JOIN Treatments AS T2 ON T1.professional_id  =  T2.professional_id JOIN Treatment_types AS T3 ON T2.treatment_type_code  =  T3.treatment_type_code
EXEC MATCH:    False
ERROR:         schema_validation: unknown table 'TreatmentsPerformed'; unknown table or alias 'TreatmentsPerformed' for column 'description'; unknown table or alias 'TreatmentsPerformed' for column 'professional_id'
WARNINGS:
  - selector: padded reranker selection with vector candidates
  - generator: using reduced ensemble budget for moderate complexity
  - execution_filter: (sqlite3.OperationalError) no such column: T2.description
[SQL: SELECT T1.first_name, T2.description FROM Professionals AS T1 JOIN Treatments AS T2 ON T1.professional_id = T2.professional_id;]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
  - execution_filter: (sqlite3.OperationalError) no such column: T2.description
[SQL: SELECT T1.first_name , T2.description FROM Professionals AS T1 JOIN Treatments AS T2 ON T1.professional_id = T2.professional_id;]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
  - execution_filter: 2/2 candidates failed
  - execution_filter: no valid candidates after execution
  - schema_validation: unknown column 'T2.description'
  - schema_validation: unknown column 'Treatments.description'
  - schema_validation: unknown table 'TreatmentsPerformed'; unknown table or alias 'TreatmentsPerformed' for column 'description'; unknown table or alias 'TreatmentsPerformed' for column 'professional_id'

========================================================================================================================
[9] QUESTION: What are each professional's first name and description of the treatment they have performed?
PREDICTED SQL: SELECT P.first_name, T.description FROM Professionals AS P JOIN Treatments AS T ON P.professional_id = T.professional_id;
GOLD SQL:      SELECT DISTINCT T1.first_name ,  T3.treatment_type_description FROM professionals AS T1 JOIN Treatments AS T2 ON T1.professional_id  =  T2.professional_id JOIN Treatment_types AS T3 ON T2.treatment_type_code  =  T3.treatment_type_code
EXEC MATCH:    False
ERROR:         schema_validation: unknown column 'T.treatment_description'
WARNINGS:
  - selector: padded reranker selection with vector candidates
  - query_sketcher: failed to parse JSON response
  - query_sketcher: structured repair unavailable (Could not parse response content as the length limit was reached - CompletionUsage(completion_tokens=2032, prompt_tokens=511, total_tokens=2543, completion_tokens_details=CompletionTokensDetails(accepted_prediction_tokens=None, audio_tokens=0, reasoning_tokens=1837, rejected_prediction_tokens=None, image_tokens=0), prompt_tokens_details=PromptTokensDetails(audio_tokens=0, cached_tokens=0, cache_write_tokens=0, video_tokens=0), cost=0.02095875, is_byok=False, cost_details={'upstream_inference_cost': 0.02095875, 'upstream_inference_prompt_cost': 0.00063875, 'upstream_inference_completions_cost': 0.02032}))
  - query_sketcher: used deterministic fallback sketch
  - generator: using reduced ensemble budget for moderate complexity
  - execution_filter: (sqlite3.OperationalError) no such table: Treatment
[SQL: SELECT T1.first_name, T2.description FROM Professionals AS T1 JOIN Treatment AS T2 ON T1.professional_id = T2.professional_id;]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
  - execution_filter: (sqlite3.OperationalError) no such table: Treatment
[SQL: SELECT T1.first_name, T2.description FROM Professionals AS T1 JOIN Treatment AS T2 ON T1.professional_id = T2.professional_id;]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
  - execution_filter: 2/2 candidates failed
  - execution_filter: no valid candidates after execution
  - schema_validation: unknown table 'Treatment'; unknown table or alias 'T2' for column 'description'; unknown table or alias 'T2' for column 'professional_id'
  - schema_validation: unknown column 'T.description'
  - schema_validation: unknown column 'T.treatment_description'

In [11]:
# dog_kennels: compact table view for the 9 hard-error rows

import pandas as pd

pd.set_option('display.max_colwidth', 200)

dog_table = pd.DataFrame([
    {
        'question': row['question'],
        'predicted_sql': row['predicted_sql'],
        'gold_sql': row['gold_sql'],
        'error_message': row.get('error_message'),
    }
    for row in predictions
    if row['db_id'] == 'dog_kennels' and row.get('error_message')
])

dog_table

,question,predicted_sql,gold_sql,error_message
0,What are the names of the dogs for which the owner spent more than 1000 for treatment?,SELECT name FROM Dogs WHERE dog_id IN (SELECT dog_id FROM Treatments GROUP BY dog_id HAVING SUM(cost) > 1000);,SELECT name FROM Dogs WHERE dog_id NOT IN( SELECT dog_id FROM Treatments GROUP BY dog_id HAVING sum(cost_of_treatment) > 1000 ),(sqlite3.OperationalError) no such column: amount\n[SQL: SELECT name FROM Dogs WHERE dog_id IN (SELECT dog_id FROM Treatments GROUP BY dog_id HAVING SUM(amount) > 1000);]\n(Background on this erro...
1,Tell me the owner id and last name of the owner who spent the most on treatments of his or her dogs.,"SELECT O.owner_id, O.last_name FROM Owners O JOIN Dogs D ON O.owner_id = D.owner_id JOIN Treatments T ON D.dog_id = T.dog_id GROUP BY O.owner_id ORDER BY SUM(T.cost) DESC LIMIT 1;","SELECT T1.owner_id , T1.last_name FROM Owners AS T1 JOIN Dogs AS T2 ON T1.owner_id = T2.owner_id JOIN Treatments AS T3 ON T2.dog_id = T3.dog_id GROUP BY T1.owner_id ORDER BY count(*) DESC LIM...",schema_validation: unknown column 'T.treatment_cost'
2,Give me the description of the treatment type whose total cost is the lowest.,SELECT T2.treatment_type_description FROM Treatments AS T1 JOIN Treatment_Types AS T2 ON T1.treatment_type_code = T2.treatment_type_code GROUP BY T2.treatment_type_description ORDER BY SUM(T1.trea...,SELECT T1.treatment_type_description FROM Treatment_types AS T1 JOIN Treatments AS T2 ON T1.treatment_type_code = T2.treatment_type_code GROUP BY T1.treatment_type_code ORDER BY sum(cost_of_trea...,schema_validation: unknown column 'T1.treatment_cost'
3,Find the id and cell phone of the professionals who operate two or more types of treatments.,"SELECT p.professional_id, p.cell_number FROM Professionals p JOIN Treatments t ON p.professional_id = t.professional_id GROUP BY p.professional_id, p.cell_number HAVING COUNT(DISTINCT t.treatment_...","SELECT T1.professional_id , T1.cell_number FROM Professionals AS T1 JOIN Treatments AS T2 ON T1.professional_id = T2.professional_id GROUP BY T1.professional_id HAVING count(*) >= 2",schema_validation: unknown column 't.treatment_code'
4,Which professionals have operated a treatment that costs less than the average? Give me theor first names and last names.,"SELECT DISTINCT P.first_name, P.last_name FROM Professionals P JOIN Treatments T ON P.professional_id = T.professional_id WHERE T.cost < (SELECT AVG(cost) FROM Treatments);","SELECT DISTINCT T1.first_name , T1.last_name FROM Professionals AS T1 JOIN Treatments AS T2 WHERE cost_of_treatment < ( SELECT avg(cost_of_treatment) FROM Treatments )",schema_validation: unknown column 'T.cost'
5,What are the cost and treatment type description of each treatment?,"SELECT T1.treatment_type_code, T2.treatment_type_description FROM Treatments AS T1 JOIN Treatment_Types AS T2 ON T1.treatment_type_code = T2.treatment_type_code;","SELECT T1.cost_of_treatment , T2.treatment_type_description FROM Treatments AS T1 JOIN treatment_types AS T2 ON T1.treatment_type_code = T2.treatment_type_code",schema_validation: unknown column 'T1.treatment_cost'
6,Show me the cost of the most recently performed treatment.,SELECT treatment_cost FROM Treatments ORDER BY treatment_date DESC LIMIT 1;,SELECT cost_of_treatment FROM Treatments ORDER BY date_of_treatment DESC LIMIT 1,(sqlite3.OperationalError) no such column: cost\n[SQL: SELECT cost FROM Treatments ORDER BY treatment_date DESC LIMIT 1;]\n(Background on this error at: https://sqlalche.me/e/20/e3q8)
7,List the first name of all the professionals along with the description of the treatment they have done.,"SELECT Professionals.first_name, Treatments.description FROM Professionals JOIN Treatments ON Professionals.professional_id = Treatments.professional_id;","SELECT DISTINCT T1.first_name , T3.treatment_type_description FROM professionals AS T1 JOIN Treatments AS T2 ON T1.professional_id = T2.professional_id JOIN Treatment_types AS T3 ON T2.treatmen...",schema_validation: unknown table 'TreatmentsPerformed'; unknown table or alias 'TreatmentsPerformed' for column 'description'; unknown table or alias 'TreatmentsPerformed' for column 'professional...
8,What are each professional's first name and description of the treatment they have performed?,"SELECT P.first_name, T.description FROM Professionals AS P JOIN Treatments AS T ON P.professional_id = T.professional_id;","SELECT DISTINCT T1.first_name , T3.treatment_type_description FROM professionals AS T1 JOIN Treatments AS T2 ON T1.professional_id = T2.professional_id JOIN Treatment_types AS T3 ON T2.treatmen...",schema_validation: unknown column 'T.treatment_description'

In [12]:
# car_1: compact table view for hard-error rows

import pandas as pd

pd.set_option('display.max_colwidth', 200)

car_table = pd.DataFrame([
    {
        'question': row['question'],
        'predicted_sql': row['predicted_sql'],
        'gold_sql': row['gold_sql'],
        'error_message': row.get('error_message'),
    }
    for row in predictions
    if row['db_id'] == 'car_1' and row.get('error_message')
])

car_table

,question,predicted_sql,gold_sql,error_message
0,Find the model of the car whose weight is below the average weight.,SELECT model FROM cars_data WHERE weight < (SELECT AVG(weight) FROM cars_data);,SELECT T1.model FROM CAR_NAMES AS T1 JOIN CARS_DATA AS T2 ON T1.MakeId = T2.Id WHERE T2.Weight < (SELECT avg(Weight) FROM CARS_DATA),(sqlite3.OperationalError) no such column: model\n[SQL: SELECT model FROM car_makers WHERE weight < (SELECT AVG(weight) FROM car_makers);]\n(Background on this error at: https://sqlalche.me/e/20/e...
1,What is the largest amount of horsepower for the models with 3 cylinders and what make is it?,SELECT Maker FROM car_makers WHERE Id IN ( SELECT Id FROM car_makers WHERE Cylinders = 3 AND Horsepower = ( SELECT MAX(Horsepower) FROM car_makers WHERE Cylinders = 3 ) );,"SELECT T2.horsepower , T1.Make FROM CAR_NAMES AS T1 JOIN CARS_DATA AS T2 ON T1.MakeId = T2.Id WHERE T2.cylinders = 3 ORDER BY T2.horsepower DESC LIMIT 1;","(sqlite3.OperationalError) no such column: Horsepower\n[SQL: SELECT MAX(Horsepower), Maker FROM car_makers WHERE Cylinders = 3;]\n(Background on this error at: https://sqlalche.me/e/20/e3q8)"
2,Which distinctive models are produced by maker with the full name General Motors or weighing more than 3500?,SELECT DISTINCT car_models.Model FROM car_models JOIN car_makers ON car_models.Maker = car_makers.Maker WHERE car_makers.FullName = 'General Motors' OR car_models.Weight > 3500;,SELECT DISTINCT T2.Model FROM CAR_NAMES AS T1 JOIN MODEL_LIST AS T2 ON T1.Model = T2.Model JOIN CAR_MAKERS AS T3 ON T2.Maker = T3.Id JOIN CARS_DATA AS T4 ON T1.MakeId = T4.Id WHERE T3.FullNa...,(sqlite3.OperationalError) no such column: Model\n[SQL: SELECT DISTINCT Model FROM car_makers WHERE FullName = 'General Motors' OR Weight > 3500;]\n(Background on this error at: https://sqlalche.m...
3,"For a volvo model, how many cylinders does the version with least accelerate have?",SELECT c.Cylinders FROM car_makers m JOIN car_models c ON c.Maker = m.Id WHERE m.Maker = 'volvo' ORDER BY c.Acceleration ASC LIMIT 1;,SELECT T1.cylinders FROM CARS_DATA AS T1 JOIN CAR_NAMES AS T2 ON T1.Id = T2.MakeId WHERE T2.Model = 'volvo' ORDER BY T1.accelerate ASC LIMIT 1;,schema_validation: unknown table 'car_models'; unknown table or alias 'c' for column 'Cylinders'; unknown table or alias 'c' for column 'Maker'; unknown table or alias 'c' for column 'Acceleration'
4,What are the different models wthat are lighter than 3500 but were not built by the Ford Motor Company?,SELECT DISTINCT m.Model FROM models m JOIN car_makers cm ON m.Maker = cm.Id WHERE m.Weight < 3500 AND cm.FullName != 'Ford Motor Company';,SELECT DISTINCT T1.model FROM MODEL_LIST AS T1 JOIN CAR_NAMES AS T2 ON T1.Model = T2.Model JOIN CARS_DATA AS T3 ON T2.MakeId = T3.Id JOIN CAR_MAKERS AS T4 ON T1.Maker = T4.Id WHERE T3.weight...,schema_validation: unknown table 'models'; unknown table or alias 'm' for column 'Model'; unknown table or alias 'm' for column 'Maker'; unknown table or alias 'm' for column 'Weight'

In [4]:
# Detailed failed examples inside the main problematic DBs
focus_rows = []
for row in predictions:
    if row['db_id'] in focus_dbs and (row.get('error_message') or not row.get('execution_match')):
        focus_rows.append({
            'db_id': row['db_id'],
            'question': row['question'],
            'predicted_sql': row['predicted_sql'],
            'gold_sql': row['gold_sql'],
            'execution_match': row['execution_match'],
            'error_message': row.get('error_message'),
            'warnings': row.get('warnings', []),
        })

print('Failed / mismatched rows in focus DBs:', len(focus_rows))
for row in focus_rows[:20]:
    print('\n' + '-' * 100)
    pprint(row, width=140)

Failed / mismatched rows in focus DBs: 140

----------------------------------------------------------------------------------------------------
{'db_id': 'car_1',
 'error_message': None,
 'execution_match': False,
 'gold_sql': 'SELECT T1.FullName ,  T1.Id ,  count(*) FROM CAR_MAKERS AS T1 JOIN MODEL_LIST AS T2 ON T1.Id  =  T2.Maker GROUP BY T1.Id;',
 'predicted_sql': 'SELECT FullName, Id, 0 AS NumberOfModels FROM car_makers;',
 'question': 'How many models does each car maker produce? List maker full name, id and the number.',
 'warnings': ['selector: padded reranker selection with vector candidates',
              'query_sketcher: failed to parse JSON response',
              'query_sketcher: structured repair unavailable (Could not parse response content as the length limit was reached - '
              'CompletionUsage(completion_tokens=2032, prompt_tokens=224, total_tokens=2256, '
              'completion_tokens_details=CompletionTokensDetails(accepted_prediction_tokens=None, audio_tokens=0, reasoning_tokens=1965, '
              'rejected_prediction_tokens=None, image_tokens=0), prompt_tokens_details=PromptTokensDetails(audio_tokens=0, '
              'cached_tokens=0, cache_write_tokens=0, video_tokens=0), cost=0.0206, is_byok=False, '
              "cost_details={'upstream_inference_cost': 0.0206, 'upstream_inference_prompt_cost': 0.00028, "
              "'upstream_inference_completions_cost': 0.02032}))",
              'query_sketcher: used deterministic fallback sketch',
              'generator: using reduced ensemble budget for moderate complexity',
              'execution_filter: (sqlite3.OperationalError) no such table: models\n'
              '[SQL: SELECT T1.FullName, T1.Id, COUNT(*) FROM car_makers AS T1 JOIN models AS T2 ON T1.Id = T2.maker_id GROUP BY T1.Id, '
              'T1.FullName;]\n'
              '(Background on this error at: https://sqlalche.me/e/20/e3q8)',
              'execution_filter: (sqlite3.OperationalError) no such table: models\n'
              '[SQL: SELECT T1.FullName , T1.Id , count(*) FROM car_makers AS T1 JOIN models AS T2 ON T1.Id = T2.maker_id GROUP BY '
              'T1.Id;]\n'
              '(Background on this error at: https://sqlalche.me/e/20/e3q8)',
              'execution_filter: 2/2 candidates failed',
              'execution_filter: no valid candidates after execution',
              "schema_validation: unknown table 'models'; unknown table or alias 'T2' for column 'maker_id'"]}

----------------------------------------------------------------------------------------------------
{'db_id': 'car_1',
 'error_message': None,
 'execution_match': False,
 'gold_sql': 'SELECT T1.FullName ,  T1.Id ,  count(*) FROM CAR_MAKERS AS T1 JOIN MODEL_LIST AS T2 ON T1.Id  =  T2.Maker GROUP BY T1.Id;',
 'predicted_sql': 'SELECT Id, FullName, 0 AS number_of_models FROM car_makers;',
 'question': 'What is the full name of each car maker, along with its id and how many models it produces?',
 'warnings': ['selector: padded reranker selection with vector candidates',
              'generator: using reduced ensemble budget for moderate complexity',
              'execution_filter: (sqlite3.OperationalError) no such table: models\n'
              '[SQL: SELECT T1.FullName, T1.Id, COUNT(*) FROM car_makers AS T1 JOIN models AS T2 ON T1.Id = T2.Maker GROUP BY T1.Id;]\n'
              '(Background on this error at: https://sqlalche.me/e/20/e3q8)',
              'execution_filter: (sqlite3.OperationalError) no such table: models\n'
              '[SQL: SELECT T1.FullName, T1.Id, COUNT(*) FROM car_makers AS T1 JOIN models AS T2 ON T1.Id = T2.Maker GROUP BY T1.Id;]\n'
              '(Background on this error at: https://sqlalche.me/e/20/e3q8)',
              'execution_filter: 2/2 candidates failed',
              'execution_filter: no valid candidates after execution',
              "schema_validation: unknown table 'models'; unknown table or alias 'T2' for column 'Maker'"]}

----------------------------------------------------------------------------------------------------
{'db_id': 'car_1',
 'error_message': None,
 'execution_match': False,
 'gold_sql': 'SELECT T1.Model FROM CAR_NAMES AS T1 JOIN CARS_DATA AS T2 ON T1.MakeId  =  T2.Id ORDER BY T2.horsepower ASC LIMIT 1;',
 'predicted_sql': 'SELECT NULL;',
 'question': 'What is the model of the car with the smallest amount of horsepower?',
 'warnings': ['query_sketcher: failed to parse JSON response',
              'query_sketcher: repaired malformed sketch with structured-output fallback',
              'execution_filter: (sqlite3.OperationalError) no such table: car\n'
              '[SQL: SELECT model FROM car ORDER BY horsepower ASC LIMIT 1;]\n'
              '(Background on this error at: https://sqlalche.me/e/20/e3q8)',
              'execution_filter: (sqlite3.OperationalError) no such table: car\n'
              '[SQL: SELECT model FROM car ORDER BY horsepower ASC LIMIT 1;]\n'
              '(Background on this error at: https://sqlalche.me/e/20/e3q8)',
              'execution_filter: (sqlite3.OperationalError) no such table: car\n'
              '[SQL: SELECT model FROM car ORDER BY horsepower ASC LIMIT 1;]\n'
              '(Background on this error at: https://sqlalche.me/e/20/e3q8)',
              'execution_filter: (sqlite3.OperationalError) no such table: car\n'
              '[SQL: SELECT model FROM car ORDER BY horsepower ASC LIMIT 1;]\n'
              '(Background on this error at: https://sqlalche.me/e/20/e3q8)',
              'execution_filter: (sqlite3.OperationalError) no such table: cars\n'
              '[SQL: SELECT model FROM cars ORDER BY horsepower ASC LIMIT 1;]\n'
              '(Background on this error at: https://sqlalche.me/e/20/e3q8)',
              'execution_filter: 5/5 candidates failed',
              'execution_filter: no valid candidates after execution',
              "schema_validation_warning: unknown unqualified column 'model'; unknown unqualified column 'horsepower'",
              "schema_validation: unknown table 'car'"]}

----------------------------------------------------------------------------------------------------
{'db_id': 'car_1',
 'error_message': '(sqlite3.OperationalError) no such column: model\n'
                  '[SQL: SELECT model FROM car_makers WHERE weight < (SELECT AVG(weight) FROM car_makers);]\n'
                  '(Background on this error at: https://sqlalche.me/e/20/e3q8)',
 'execution_match': False,
 'gold_sql': 'SELECT T1.model FROM CAR_NAMES AS T1 JOIN CARS_DATA AS T2 ON T1.MakeId  =  T2.Id WHERE T2.Weight  <  (SELECT avg(Weight) '
             'FROM CARS_DATA)',
 'predicted_sql': 'SELECT model FROM cars_data WHERE weight < (SELECT AVG(weight) FROM cars_data);',
 'question': 'Find the model of the car whose weight is below the average weight.',
 'warnings': ['query_sketcher: failed to parse JSON response',
              'query_sketcher: repaired malformed sketch with structured-output fallback',
              'generator: using reduced ensemble budget for moderate complexity',
              'execution_filter: (sqlite3.OperationalError) no such column: model\n'
              '[SQL: SELECT model FROM cars_data WHERE weight < (SELECT AVG(weight) FROM cars_data);]\n'
              '(Background on this error at: https://sqlalche.me/e/20/e3q8)',
              'execution_filter: (sqlite3.OperationalError) no such column: model\n'
              '[SQL: SELECT model FROM cars_data WHERE weight < (SELECT AVG(weight) FROM cars_data);]\n'
              '(Background on this error at: https://sqlalche.me/e/20/e3q8)',
              'execution_filter: 2/2 candidates failed',
              'execution_filter: no valid candidates after execution',
              "schema_validation_warning: unknown unqualified column 'weight'; unknown unqualified column 'model'",
              "schema_validation_warning: unknown unqualified column 'weight'; unknown unqualified column 'model'",
              "schema_validation_warning: unknown unqualified column 'weight'; unknown unqualified column 'model'"]}

----------------------------------------------------------------------------------------------------
{'db_id': 'car_1',
 'error_message': None,
 'execution_match': False,
 'gold_sql': 'SELECT DISTINCT T1.Maker FROM CAR_MAKERS AS T1 JOIN MODEL_LIST AS T2 ON T1.Id  =  T2.Maker JOIN CAR_NAMES AS T3 ON T2.model  '
             "=  T3.model JOIN CARS_DATA AS T4 ON T3.MakeId  =  T4.id WHERE T4.year  =  '1970';",
 'predicted_sql': 'SELECT DISTINCT Maker FROM car_makers;',
 'question': 'Find the name of the makers that produced some cars in the year of 1970?',
 'warnings': ['execution_filter: (sqlite3.OperationalError) no such table: car_models\n'
              '[SQL: SELECT DISTINCT T1.Maker FROM car_makers AS T1 JOIN car_models AS T2 ON T1.Id = T2.Maker_Id WHERE T2.Year = 1970;]\n'
              '(Background on this error at: https://sqlalche.me/e/20/e3q8)',
              'execution_filter: (sqlite3.OperationalError) no such table: car_models\n'
              '[SQL: SELECT DISTINCT T1.Maker FROM car_makers AS T1 JOIN car_models AS T2 ON T1.Id = T2.Maker_Id WHERE T2.Year = 1970;]\n'
              '(Background on this error at: https://sqlalche.me/e/20/e3q8)',
              'execution_filter: (sqlite3.OperationalError) no such table: car_model\n'
              '[SQL: SELECT DISTINCT T1.Maker FROM car_makers AS T1 JOIN car_model AS T2 ON T1.Id = T2.maker_id WHERE T2.year = 1970;]\n'
              '(Background on this error at: https://sqlalche.me/e/20/e3q8)',
              'execution_filter: 3/4 candidates failed',
              'execution_filter: skipped judge for safe simple query with valid candidate']}

----------------------------------------------------------------------------------------------------
{'db_id': 'car_1',
 'error_message': None,
 'execution_match': False,
 'gold_sql': 'SELECT DISTINCT T1.Maker FROM CAR_MAKERS AS T1 JOIN MODEL_LIST AS T2 ON T1.Id  =  T2.Maker JOIN CAR_NAMES AS T3 ON T2.model  '
             "=  T3.model JOIN CARS_DATA AS T4 ON T3.MakeId  =  T4.id WHERE T4.year  =  '1970';",
 'predicted_sql': 'SELECT DISTINCT Maker FROM car_makers;',
 'question': 'What is the name of the different car makers who produced a car in 1970?',
 'warnings': ['query_sketcher: failed to parse JSON response',
              'query_sketcher: repaired malformed sketch with structured-output fallback',
              'execution_filter: (sqlite3.OperationalError) no such table: cars\n'
              '[SQL: SELECT DISTINCT T1.FullName FROM car_makers AS T1 JOIN cars AS T2 ON T1.Maker = T2.Maker WHERE T2.year = 1970;]\n'
              '(Background on this error at: https://sqlalche.me/e/20/e3q8)',
              'execution_filter: (sqlite3.OperationalError) no such table: cars\n'
              '[SQL: SELECT DISTINCT T2.FullName FROM car_makers AS T1 JOIN cars AS T2 ON T1.Id = T2.maker_id WHERE T2.year = 1970;]\n'
              '(Background on this error at: https://sqlalche.me/e/20/e3q8)',
              'execution_filter: (sqlite3.OperationalError) no such table: cars\n'
              '[SQL: SELECT DISTINCT T1.FullName FROM car_makers AS T1 JOIN cars AS T2 ON T1.Maker = T2.Maker WHERE T2.year = 1970;]\n'
              '(Background on this error at: https://sqlalche.me/e/20/e3q8)',
              'execution_filter: 3/5 candidates failed',
              'execution_filter: skipped judge for safe simple query with valid candidate']}

----------------------------------------------------------------------------------------------------
{'db_id': 'car_1',
 'error_message': None,
 'execution_match': False,
 'gold_sql': 'SELECT T2.Make ,  T1.Year FROM CARS_DATA AS T1 JOIN CAR_NAMES AS T2 ON T1.Id  =  T2.MakeId WHERE T1.Year  =  (SELECT '
             'min(YEAR) FROM CARS_DATA);',
 'predicted_sql': 'SELECT Maker FROM car_makers;',
 'question': 'Find the make and production time of the cars that were produced in the earliest year?',
 'warnings': ['query_sketcher: failed to parse JSON response',
              'query_sketcher: structured repair unavailable (Could not parse response content as the length limit was reached - '
              'CompletionUsage(completion_tokens=2032, prompt_tokens=226, total_tokens=2258, '
              'completion_tokens_details=CompletionTokensDetails(accepted_prediction_tokens=None, audio_tokens=0, reasoning_tokens=1587, '
              'rejected_prediction_tokens=None, image_tokens=0), prompt_tokens_details=PromptTokensDetails(audio_tokens=0, '
              'cached_tokens=0, cache_write_tokens=0, video_tokens=0), cost=0.0206025, is_byok=False, '
              "cost_details={'upstream_inference_cost': 0.0206025, 'upstream_inference_prompt_cost': 0.0002825, "
              "'upstream_inference_completions_cost': 0.02032}))",
              'query_sketcher: used deterministic fallback sketch',
              'generator: using reduced ensemble budget for moderate complexity',
              'execution_filter: (sqlite3.OperationalError) no such column: Production_time\n'
              '[SQL: SELECT Maker, Production_time FROM car_makers WHERE Production_time = (SELECT MIN(Production_time) FROM '
              'car_makers);]\n'
              '(Background on this error at: https://sqlalche.me/e/20/e3q8)',
              'execution_filter: (sqlite3.OperationalError) no such column: production_time\n'
              '[SQL: SELECT Maker, production_time FROM car_makers WHERE production_year = (SELECT MIN(production_year) FROM '
              'car_makers);]\n'
              '(Background on this error at: https://sqlalche.me/e/20/e3q8)',
              'execution_filter: 2/2 candidates failed',
              'execution_filter: no valid candidates after execution',
              "schema_validation_warning: unknown unqualified column 'Production_time'"]}

----------------------------------------------------------------------------------------------------
{'db_id': 'car_1',
 'error_message': None,
 'execution_match': False,
 'gold_sql': 'SELECT T2.Make ,  T1.Year FROM CARS_DATA AS T1 JOIN CAR_NAMES AS T2 ON T1.Id  =  T2.MakeId WHERE T1.Year  =  (SELECT '
             'min(YEAR) FROM CARS_DATA);',
 'predicted_sql': 'SELECT Maker FROM car_makers LIMIT 1;',
 'question': 'What is the maker of the carr produced in the earliest year and what year was it?',
 'warnings': ['query_sketcher: failed to parse JSON response',
              'query_sketcher: structured repair unavailable (Could not parse response content as the length limit was reached - '
              'CompletionUsage(completion_tokens=2033, prompt_tokens=227, total_tokens=2260, '
              'completion_tokens_details=CompletionTokensDetails(accepted_prediction_tokens=None, audio_tokens=0, reasoning_tokens=1667, '
              'rejected_prediction_tokens=None, image_tokens=0), prompt_tokens_details=PromptTokensDetails(audio_tokens=0, '
              'cached_tokens=0, cache_write_tokens=0, video_tokens=0), cost=0.02061375, is_byok=False, '
              "cost_details={'upstream_inference_cost': 0.02061375, 'upstream_inference_prompt_cost': 0.00028375, "
              "'upstream_inference_completions_cost': 0.02033}))",
              'query_sketcher: used deterministic fallback sketch',
              'generator: using reduced ensemble budget for moderate complexity',
              'execution_filter: (sqlite3.OperationalError) no such column: Year\n'
              '[SQL: SELECT Maker, Year FROM car_makers ORDER BY Year ASC LIMIT 1;]\n'
              '(Background on this error at: https://sqlalche.me/e/20/e3q8)',
              'execution_filter: (sqlite3.OperationalError) no such column: Year\n'
              '[SQL: SELECT Maker , Year FROM car_makers ORDER BY Year ASC LIMIT 1;]\n'
              '(Background on this error at: https://sqlalche.me/e/20/e3q8)',
              'execution_filter: 2/2 candidates failed',
              'execution_filter: no valid candidates after execution',
              "schema_validation_warning: unknown unqualified column 'Year'"]}

----------------------------------------------------------------------------------------------------
{'db_id': 'car_1',
 'error_message': None,
 'execution_match': False,
 'gold_sql': 'SELECT DISTINCT T1.model FROM MODEL_LIST AS T1 JOIN CAR_NAMES AS T2 ON T1.model  =  T2.model JOIN CARS_DATA AS T3 ON '
             'T2.MakeId  =  T3.id WHERE T3.year  >  1980;',
 'predicted_sql': 'SELECT DISTINCT Maker FROM car_makers WHERE Id IN (SELECT Id FROM car_makers WHERE Id > 0);',
 'question': 'Which distinct car models are the produced after 1980?',
 'warnings': ['query_sketcher: failed to parse JSON response',
              'query_sketcher: repaired malformed sketch with structured-output fallback',
              'execution_filter: (sqlite3.OperationalError) no such table: models\n'
              '[SQL: SELECT DISTINCT model FROM models WHERE year > 1980;]\n'
              '(Background on this error at: https://sqlalche.me/e/20/e3q8)',
              'execution_filter: (sqlite3.OperationalError) no such table: models\n'
              '[SQL: SELECT DISTINCT model FROM models WHERE year > 1980;]\n'
              '(Background on this error at: https://sqlalche.me/e/20/e3q8)',
              'execution_filter: (sqlite3.OperationalError) no such table: models\n'
              '[SQL: SELECT DISTINCT model FROM models WHERE year > 1980;]\n'
              '(Background on this error at: https://sqlalche.me/e/20/e3q8)',
              'execution_filter: 3/3 candidates failed',
              'execution_filter: no valid candidates after execution',
              "schema_validation_warning: unknown unqualified column 'model'; unknown unqualified column 'year'",
              "schema_validation: unknown table 'models'"]}

----------------------------------------------------------------------------------------------------
{'db_id': 'car_1',
 'error_message': None,
 'execution_match': False,
 'gold_sql': 'SELECT Count(*) ,  T2.FullName ,  T2.id FROM MODEL_LIST AS T1 JOIN CAR_MAKERS AS T2 ON T1.Maker  =  T2.Id GROUP BY T2.id;',
 'predicted_sql': 'SELECT count(*), FullName FROM car_makers GROUP BY FullName;',
 'question': 'How many car models are produced by each maker? List the count and the maker full name.',
 'warnings': ['selector: padded reranker selection with vector candidates',
              'query_sketcher: failed to parse JSON response',
              'query_sketcher: structured repair unavailable (Could not parse response content as the length limit was reached - '
              'CompletionUsage(completion_tokens=2013, prompt_tokens=230, total_tokens=2243, '
              'completion_tokens_details=CompletionTokensDetails(accepted_prediction_tokens=None, audio_tokens=0, reasoning_tokens=2013, '
              'rejected_prediction_tokens=None, image_tokens=0), prompt_tokens_details=PromptTokensDetails(audio_tokens=0, '
              'cached_tokens=203, cache_write_tokens=0, video_tokens=0), cost=0.020189125, is_byok=False, '
              "cost_details={'upstream_inference_cost': 0.020189125, 'upstream_inference_prompt_cost': 5.9125e-05, "
              "'upstream_inference_completions_cost': 0.02013}))",
              'query_sketcher: used deterministic fallback sketch',
              'generator: using reduced ensemble budget for moderate complexity']}

----------------------------------------------------------------------------------------------------
{'db_id': 'car_1',
 'error_message': None,
 'execution_match': False,
 'gold_sql': 'SELECT Count(*) ,  T2.FullName ,  T2.id FROM MODEL_LIST AS T1 JOIN CAR_MAKERS AS T2 ON T1.Maker  =  T2.Id GROUP BY T2.id;',
 'predicted_sql': 'SELECT count(*), Id, FullName FROM car_makers GROUP BY Id;',
 'question': 'What is the number of car models that are produced by each maker and what is the id and full name of each maker?',
 'warnings': ['selector: padded reranker selection with vector candidates',
              'query_sketcher: failed to parse JSON response',

In [5]:
# Clearly wrong predictions outside the main problematic DBs
# These are especially useful before prompt tuning because they reveal global failure modes.
other_failures = []
for row in predictions:
    if row['db_id'] in focus_dbs:
        continue
    if row.get('error_message') or not row.get('execution_match'):
        other_failures.append({
            'db_id': row['db_id'],
            'question': row['question'],
            'predicted_sql': row['predicted_sql'],
            'gold_sql': row['gold_sql'],
            'execution_match': row['execution_match'],
            'error_message': row.get('error_message'),
            'warnings': row.get('warnings', []),
        })

print('Other failed / mismatched rows:', len(other_failures))
for row in other_failures[:20]:
    print('\n' + '-' * 100)
    pprint(row, width=140)

Other failed / mismatched rows: 146

----------------------------------------------------------------------------------------------------
{'db_id': 'concert_singer',
 'error_message': "schema_validation: unknown column 'c.Attendance'",
 'execution_match': False,
 'gold_sql': 'SELECT name ,  capacity FROM stadium ORDER BY average DESC LIMIT 1',
 'predicted_sql': 'SELECT s.Name, s.Capacity FROM stadium s JOIN concert c ON s.Stadium_ID = c.Stadium_ID GROUP BY s.Stadium_ID, s.Name, '
                  's.Capacity ORDER BY AVG(c.Attendance) DESC LIMIT 1;',
 'question': 'What is the name and capacity for the stadium with highest average attendance?',
 'warnings': ['selector: padded reranker selection with vector candidates',
              'generator: using reduced ensemble budget for moderate complexity',
              'execution_filter: (sqlite3.OperationalError) no such column: Attendance\n'
              '[SQL: SELECT Name, Capacity FROM stadium GROUP BY Stadium_ID ORDER BY AVG(Attendance) DESC LIMIT 1;]\n'
              '(Background on this error at: https://sqlalche.me/e/20/e3q8)',
              'execution_filter: (sqlite3.OperationalError) no such column: Attendance\n'
              '[SQL: SELECT Name, Capacity FROM stadium GROUP BY Stadium_ID ORDER BY AVG(Attendance) DESC LIMIT 1;]\n'
              '(Background on this error at: https://sqlalche.me/e/20/e3q8)',
              'execution_filter: 2/2 candidates failed',
              'execution_filter: no valid candidates after execution',
              "schema_validation_warning: unknown unqualified column 'Attendance'",
              "schema_validation: unknown column 'c.Attendance'",
              "schema_validation: unknown column 'c.Attendance'"]}

----------------------------------------------------------------------------------------------------
{'db_id': 'concert_singer',
 'error_message': "schema_validation: unknown column 'c.Attendance'",
 'execution_match': False,
 'gold_sql': 'SELECT name ,  capacity FROM stadium ORDER BY average DESC LIMIT 1',
 'predicted_sql': 'SELECT s.Name, s.Capacity FROM stadium s JOIN concert c ON s.Stadium_ID = c.Stadium_ID GROUP BY s.Stadium_ID ORDER BY '
                  'AVG(c.Attendance) DESC LIMIT 1;',
 'question': 'What is the name and capacity for the stadium with the highest average attendance?',
 'warnings': ['selector: padded reranker selection with vector candidates',
              'query_sketcher: failed to parse JSON response',
              'query_sketcher: repaired malformed sketch with structured-output fallback',
              'generator: using reduced ensemble budget for moderate complexity',
              'execution_filter: (sqlite3.OperationalError) no such column: Average_Attendance\n'
              '[SQL: SELECT Name, Capacity FROM stadium ORDER BY Average_Attendance DESC LIMIT 1;]\n'
              '(Background on this error at: https://sqlalche.me/e/20/e3q8)',
              'execution_filter: (sqlite3.OperationalError) no such column: Average_Attendance\n'
              '[SQL: SELECT Name , Capacity FROM stadium ORDER BY Average_Attendance DESC LIMIT 1;]\n'
              '(Background on this error at: https://sqlalche.me/e/20/e3q8)',
              'execution_filter: 2/2 candidates failed',
              'execution_filter: no valid candidates after execution',
              "schema_validation_warning: unknown unqualified column 'Average_Attendance'",
              "schema_validation: unknown column 'c.Attendance'",
              "schema_validation: unknown column 'c.Attendance'"]}

----------------------------------------------------------------------------------------------------
{'db_id': 'concert_singer',
 'error_message': None,
 'execution_match': False,
 'gold_sql': 'SELECT T2.name ,  count(*) FROM concert AS T1 JOIN stadium AS T2 ON T1.stadium_id  =  T2.stadium_id GROUP BY T1.stadium_id',
 'predicted_sql': 'SELECT Stadium_ID , count(*) FROM concert GROUP BY Stadium_ID;',
 'question': 'For each stadium, how many concerts play there?',
 'warnings': ['selector: padded reranker selection with vector candidates',
              'execution_filter: skipped judge for safe simple query with valid candidate']}

----------------------------------------------------------------------------------------------------
{'db_id': 'concert_singer',
 'error_message': None,
 'execution_match': False,
 'gold_sql': 'SELECT T2.name FROM singer_in_concert AS T1 JOIN singer AS T2 ON T1.singer_id  =  T2.singer_id JOIN concert AS T3 ON '
             'T1.concert_id  =  T3.concert_id WHERE T3.year  =  2014',
 'predicted_sql': 'SELECT DISTINCT T1.Name FROM singer AS T1 JOIN singer_in_concert AS T2 ON T1.Singer_ID = T2.Singer_ID JOIN concert AS '
                  "T3 ON T2.concert_ID = T3.concert_ID WHERE T3.Year = '2014';",
 'question': 'List all singer names in concerts in year 2014.',
 'warnings': ['generator: using reduced ensemble budget for moderate complexity']}

----------------------------------------------------------------------------------------------------
{'db_id': 'concert_singer',
 'error_message': None,
 'execution_match': False,
 'gold_sql': 'SELECT T2.name FROM singer_in_concert AS T1 JOIN singer AS T2 ON T1.singer_id  =  T2.singer_id JOIN concert AS T3 ON '
             'T1.concert_id  =  T3.concert_id WHERE T3.year  =  2014',
 'predicted_sql': 'SELECT DISTINCT T1.Name FROM singer AS T1 JOIN singer_in_concert AS T2 ON T1.Singer_ID = T2.Singer_ID JOIN concert AS '
                  "T3 ON T2.concert_ID = T3.concert_ID WHERE T3.Year = '2014';",
 'question': 'What are the names of the singers who performed in a concert in 2014?',
 'warnings': []}

----------------------------------------------------------------------------------------------------
{'db_id': 'concert_singer',
 'error_message': None,
 'execution_match': False,
 'gold_sql': 'SELECT count(*) FROM concert AS T1 JOIN stadium AS T2 ON T1.stadium_id  =  T2.stadium_id ORDER BY T2.Capacity DESC LIMIT 1',
 'predicted_sql': 'SELECT count(*) FROM concert WHERE Stadium_ID IN (SELECT Stadium_ID FROM stadium WHERE Capacity = (SELECT max(Capacity) '
                  'FROM stadium));',
 'question': 'Find the number of concerts happened in the stadium with the highest capacity.',
 'warnings': ['selector: padded reranker selection with vector candidates',
              'generator: using reduced ensemble budget for moderate complexity',
              "schema_validation_warning: unknown unqualified column 'Capacity'"]}

----------------------------------------------------------------------------------------------------
{'db_id': 'concert_singer',
 'error_message': None,
 'execution_match': False,
 'gold_sql': 'SELECT count(*) FROM concert AS T1 JOIN stadium AS T2 ON T1.stadium_id  =  T2.stadium_id ORDER BY T2.Capacity DESC LIMIT 1',
 'predicted_sql': 'SELECT count(*) FROM concert WHERE Stadium_ID = (SELECT Stadium_ID FROM stadium ORDER BY Capacity DESC LIMIT 1);',
 'question': 'What are the number of concerts that occurred in the stadium with the largest capacity?',
 'warnings': ['selector: padded reranker selection with vector candidates',
              'generator: using reduced ensemble budget for moderate complexity',
              "schema_validation_warning: unknown unqualified column 'Capacity'"]}

----------------------------------------------------------------------------------------------------
{'db_id': 'pets_1',
 'error_message': None,
 'execution_match': False,
 'gold_sql': 'SELECT T1.fname ,  T1.age FROM student AS T1 JOIN has_pet AS T2 ON T1.stuid  =  T2.stuid JOIN pets AS T3 ON T3.petid  =  '
             "T2.petid WHERE T3.pettype  =  'dog' AND T1.stuid NOT IN (SELECT T1.stuid FROM student AS T1 JOIN has_pet AS T2 ON T1.stuid  "
             "=  T2.stuid JOIN pets AS T3 ON T3.petid  =  T2.petid WHERE T3.pettype  =  'cat')",
 'predicted_sql': 'SELECT T1.Fname, T1.Age FROM Student AS T1 JOIN Has_Pet AS T2 ON T1.StuID = T2.StuID JOIN Pets AS T3 ON T2.PetID = '
                  "T3.PetID WHERE T3.PetType = 'dog' EXCEPT SELECT T1.Fname, T1.Age FROM Student AS T1 JOIN Has_Pet AS T2 ON T1.StuID = "
                  "T2.StuID JOIN Pets AS T3 ON T2.PetID = T3.PetID WHERE T3.PetType = 'cat';",
 'question': 'Find the first name and age of students who have a dog but do not have a cat as a pet.',
 'warnings': ['generator: using reduced ensemble budget for moderate complexity']}

----------------------------------------------------------------------------------------------------
{'db_id': 'pets_1',
 'error_message': None,
 'execution_match': False,
 'gold_sql': 'SELECT T1.fname ,  T1.age FROM student AS T1 JOIN has_pet AS T2 ON T1.stuid  =  T2.stuid JOIN pets AS T3 ON T3.petid  =  '
             "T2.petid WHERE T3.pettype  =  'dog' AND T1.stuid NOT IN (SELECT T1.stuid FROM student AS T1 JOIN has_pet AS T2 ON T1.stuid  "
             "=  T2.stuid JOIN pets AS T3 ON T3.petid  =  T2.petid WHERE T3.pettype  =  'cat')",
 'predicted_sql': 'SELECT T1.Fname FROM Student AS T1 JOIN Has_Pet AS T2 ON T1.StuID = T2.StuID JOIN Pets AS T3 ON T2.PetID = T3.PetID '
                  "WHERE T3.PetType = 'dog' EXCEPT SELECT T1.Fname FROM Student AS T1 JOIN Has_Pet AS T2 ON T1.StuID = T2.StuID JOIN Pets "
                  "AS T3 ON T2.PetID = T3.PetID WHERE T3.PetType = 'cat';",
 'question': 'What is the first name of every student who has a dog but does not have a cat?',
 'warnings': ['selector: padded reranker selection with vector candidates',
              'generator: using reduced ensemble budget for moderate complexity']}

----------------------------------------------------------------------------------------------------
{'db_id': 'flight_2',
 'error_message': None,
 'execution_match': False,
 'gold_sql': 'SELECT Country FROM AIRLINES WHERE Airline  =  "JetBlue Airways"',
 'predicted_sql': "SELECT Country FROM airlines WHERE Airline = 'Jetblue Airways';",
 'question': 'What country is Jetblue Airways affiliated with?',
 'warnings': ['selector: padded reranker selection with vector candidates',
              'execution_filter: skipped judge for safe simple query with valid candidate']}

----------------------------------------------------------------------------------------------------
{'db_id': 'flight_2',
 'error_message': None,
 'execution_match': False,
 'gold_sql': 'SELECT Abbreviation FROM AIRLINES WHERE Airline  =  "JetBlue Airways"',
 'predicted_sql': "SELECT Abbreviation FROM airlines WHERE Airline = 'Jetblue Airways';",
 'question': 'Which abbreviation corresponds to Jetblue Airways?',
 'warnings': ['selector: padded reranker selection with vector candidates',
              'execution_filter: skipped judge for safe simple query with valid candidate']}

----------------------------------------------------------------------------------------------------
{'db_id': 'flight_2',
 'error_message': None,
 'execution_match': False,
 'gold_sql': 'SELECT AirportCode ,  AirportName FROM AIRPORTS WHERE city  =  "Anthony"',
 'predicted_sql': "SELECT AirportCode, AirportName FROM airports WHERE TRIM(City) = 'Anthony';",
 'question': 'List the airport code and name in the city of Anthony.',
 'warnings': ['selector: padded reranker selection with vector candidates',
              'execution_filter: skipped judge for safe simple query with valid candidate']}

----------------------------------------------------------------------------------------------------
{'db_id': 'flight_2',
 'error_message': None,
 'execution_match': False,
 'gold_sql': 'SELECT City ,  Country FROM AIRPORTS WHERE AirportName  =  "Alton"',
 'predicted_sql': "SELECT TRIM(City), TRIM(Country) FROM airports WHERE AirportName LIKE '%Alton%';",
 'question': 'Which city and country is the Alton airport at?',
 'warnings': ['selector: padded reranker selection with vector candidates',
              'execution_filter: skipped judge for safe simple query with valid candidate']}

----------------------------------------------------------------------------------------------------
{'db_id': 'flight_2',
 'error_message': None,
 'execution_match': False,
 'gold_sql': 'SELECT City ,  Country FROM AIRPORTS WHERE AirportName  =  "Alton"',
 'predicted_sql': "SELECT City , Country FROM airports WHERE AirportName LIKE '%Alton%';",
 'question': 'Give the city and country for the Alton airport.',
 'warnings': ['selector: padded reranker selection with vector candidates',
              'execution_filter: skipped judge for safe simple query with valid candidate']}

----------------------------------------------------------------------------------------------------
{'db_id': 'flight_2',
 'error_message': 'benchmark_timeout: example exceeded 660s',
 'execution_match': False,
 'gold_sql': 'SELECT AirportName FROM AIRPORTS WHERE City = "Aberdeen"',
 'predicted_sql': '',
 'question': "What are airport names at City 'Aberdeen'?",
 'warnings': []}

----------------------------------------------------------------------------------------------------
{'db_id': 'flight_2',
 'error_message': None,
 'execution_match': False,
 'gold_sql': 'SELECT AirportName FROM AIRPORTS WHERE City = "Aberdeen"',
 'predicted_sql': "SELECT AirportName FROM airports WHERE TRIM(City) = 'Aberdeen';",
 'question': 'What are the names of airports in Aberdeen?',
 'warnings': ['selector: padded reranker selection with vector candidates',
              'execution_filter: skipped judge for safe simple query with valid candidate']}

----------------------------------------------------------------------------------------------------
{'db_id': 'flight_2',
 'error_message': None,
 'execution_match': False,
 'gold_sql': 'SELECT count(*) FROM FLIGHTS WHERE SourceAirport  =  "APG"',
 'predicted_sql': "SELECT count(*) FROM flights WHERE TRIM(SourceAirport) = 'APG';",
 'question': "How many flights depart from 'APG'?",
 'warnings': ['selector: padded reranker selection with vector candidates',
              'execution_filter: skipped judge for safe simple query with valid candidate']}

----------------------------------------------------------------------------------------------------
{'db_id': 'flight_2',
 'error_message': None,
 'execution_match': False,
 'gold_sql': 'SELECT count(*) FROM FLIGHTS WHERE SourceAirport  =  "APG"',
 'predicted_sql': "SELECT count(*) FROM flights WHERE TRIM(SourceAirport) = 'APG';",
 'question': "Count the number of flights departing from 'APG'.",
 'warnings': ['selector: padded reranker selection with vector candidates',
              'execution_filter: skipped judge for safe simple query with valid candidate']}

----------------------------------------------------------------------------------------------------
{'db_id': 'flight_2',
 'error_message': None,
 'execution_match': False,
 'gold_sql': 'SELECT count(*) FROM FLIGHTS WHERE DestAirport  =  "ATO"',
 'predicted_sql': "SELECT count(*) FROM flights WHERE TRIM(DestAirport) = 'ATO';",
 'question': 'How many flights have destination ATO?',
 'warnings': ['selector: padded reranker selection with vector candidates',
              'execution_filter: skipped judge for safe simple query with valid candidate']}

----------------------------------------------------------------------------------------------------
{'db_id': 'flight_2',
 'error_message': 'benchmark_timeout: example exceeded 660s',
 'execution_match': False,
 'gold_sql': 'SELECT count(*) FROM FLIGHTS AS T1 JOIN AIRPORTS AS T2 ON T1.SourceAirport  =  T2.AirportCode WHERE T2.City  =  "Aberdeen"',
 'predicted_sql': '',
 'question': 'Return the number of flights departing from Aberdeen.',
 'warnings': []}

In [6]:
# Heuristic buckets for fast prompt-tuning ideas
buckets = Counter()
for row in predictions:
    sql = (row.get('predicted_sql') or '').upper()
    warnings = ' | '.join(row.get('warnings', []))
    err = row.get('error_message') or ''

    if 'TRIM(' in sql or 'LOWER(' in sql or 'UPPER(' in sql or 'CAST(' in sql:
        buckets['value_normalization_or_cast'] += 1
    if 'schema_validation:' in warnings or 'schema_validation:' in err:
        buckets['schema_grounding_failures'] += 1
    if 'failed to parse JSON response' in warnings:
        buckets['sketch_parse_failures'] += 1
    if 'repaired malformed sketch' in warnings:
        buckets['sketch_repair_used'] += 1
    if 'skipped judge for safe simple query' in warnings:
        buckets['cheap_path_used'] += 1

buckets

Counter({'cheap_path_used': 402,
         'sketch_parse_failures': 111,
         'schema_grounding_failures': 73,
         'value_normalization_or_cast': 60,
         'sketch_repair_used': 59})

In [7]:
# Helper: inspect one database in detail
def inspect_db(db_id: str, limit: int = 20):
    rows = []
    for row in predictions:
        if row['db_id'] != db_id:
            continue
        if row.get('error_message') or not row.get('execution_match'):
            rows.append(row)
    print(f'{db_id}: {len(rows)} failed/mismatched rows')
    for row in rows[:limit]:
        print('\n' + '-' * 100)
        print('Q:', row['question'])
        print('PRED:', row['predicted_sql'])
        print('GOLD:', row['gold_sql'])
        print('EXEC:', row['execution_match'], 'ERR:', row.get('error_message'))
        print('WARNINGS:', row.get('warnings', []))

# Example:
# inspect_db('car_1')

In [8]:
inspect_db('car_1')

car_1: 59 failed/mismatched rows

----------------------------------------------------------------------------------------------------
Q: How many models does each car maker produce? List maker full name, id and the number.
PRED: SELECT FullName, Id, 0 AS NumberOfModels FROM car_makers;
GOLD: SELECT T1.FullName ,  T1.Id ,  count(*) FROM CAR_MAKERS AS T1 JOIN MODEL_LIST AS T2 ON T1.Id  =  T2.Maker GROUP BY T1.Id;
EXEC: False ERR: None
WARNINGS: ['selector: padded reranker selection with vector candidates', 'query_sketcher: failed to parse JSON response', "query_sketcher: structured repair unavailable (Could not parse response content as the length limit was reached - CompletionUsage(completion_tokens=2032, prompt_tokens=224, total_tokens=2256, completion_tokens_details=CompletionTokensDetails(accepted_prediction_tokens=None, audio_tokens=0, reasoning_tokens=1965, rejected_prediction_tokens=None, image_tokens=0), prompt_tokens_details=PromptTokensDetails(audio_tokens=0, cached_tokens=0, cache_write_tokens=0, video_tokens=0), cost=0.0206, is_byok=False, cost_details={'upstream_inference_cost': 0.0206, 'upstream_inference_prompt_cost': 0.00028, 'upstream_inference_completions_cost': 0.02032}))", 'query_sketcher: used deterministic fallback sketch', 'generator: using reduced ensemble budget for moderate complexity', 'execution_filter: (sqlite3.OperationalError) no such table: models\n[SQL: SELECT T1.FullName, T1.Id, COUNT(*) FROM car_makers AS T1 JOIN models AS T2 ON T1.Id = T2.maker_id GROUP BY T1.Id, T1.FullName;]\n(Background on this error at: https://sqlalche.me/e/20/e3q8)', 'execution_filter: (sqlite3.OperationalError) no such table: models\n[SQL: SELECT T1.FullName , T1.Id , count(*) FROM car_makers AS T1 JOIN models AS T2 ON T1.Id = T2.maker_id GROUP BY T1.Id;]\n(Background on this error at: https://sqlalche.me/e/20/e3q8)', 'execution_filter: 2/2 candidates failed', 'execution_filter: no valid candidates after execution', "schema_validation: unknown table 'models'; unknown table or alias 'T2' for column 'maker_id'"]

----------------------------------------------------------------------------------------------------
Q: What is the full name of each car maker, along with its id and how many models it produces?
PRED: SELECT Id, FullName, 0 AS number_of_models FROM car_makers;
GOLD: SELECT T1.FullName ,  T1.Id ,  count(*) FROM CAR_MAKERS AS T1 JOIN MODEL_LIST AS T2 ON T1.Id  =  T2.Maker GROUP BY T1.Id;
EXEC: False ERR: None
WARNINGS: ['selector: padded reranker selection with vector candidates', 'generator: using reduced ensemble budget for moderate complexity', 'execution_filter: (sqlite3.OperationalError) no such table: models\n[SQL: SELECT T1.FullName, T1.Id, COUNT(*) FROM car_makers AS T1 JOIN models AS T2 ON T1.Id = T2.Maker GROUP BY T1.Id;]\n(Background on this error at: https://sqlalche.me/e/20/e3q8)', 'execution_filter: (sqlite3.OperationalError) no such table: models\n[SQL: SELECT T1.FullName, T1.Id, COUNT(*) FROM car_makers AS T1 JOIN models AS T2 ON T1.Id = T2.Maker GROUP BY T1.Id;]\n(Background on this error at: https://sqlalche.me/e/20/e3q8)', 'execution_filter: 2/2 candidates failed', 'execution_filter: no valid candidates after execution', "schema_validation: unknown table 'models'; unknown table or alias 'T2' for column 'Maker'"]

----------------------------------------------------------------------------------------------------
Q: What is the model of the car with the smallest amount of horsepower?
PRED: SELECT NULL;
GOLD: SELECT T1.Model FROM CAR_NAMES AS T1 JOIN CARS_DATA AS T2 ON T1.MakeId  =  T2.Id ORDER BY T2.horsepower ASC LIMIT 1;
EXEC: False ERR: None
WARNINGS: ['query_sketcher: failed to parse JSON response', 'query_sketcher: repaired malformed sketch with structured-output fallback', 'execution_filter: (sqlite3.OperationalError) no such table: car\n[SQL: SELECT model FROM car ORDER BY horsepower ASC LIMIT 1;]\n(Background on this error at: https://sqlalche.me/e/20/e3q8)', 'execution_filter: (sqlite3.OperationalError) no such table: car\n[SQL: SELECT model FROM car ORDER BY horsepower ASC LIMIT 1;]\n(Background on this error at: https://sqlalche.me/e/20/e3q8)', 'execution_filter: (sqlite3.OperationalError) no such table: car\n[SQL: SELECT model FROM car ORDER BY horsepower ASC LIMIT 1;]\n(Background on this error at: https://sqlalche.me/e/20/e3q8)', 'execution_filter: (sqlite3.OperationalError) no such table: car\n[SQL: SELECT model FROM car ORDER BY horsepower ASC LIMIT 1;]\n(Background on this error at: https://sqlalche.me/e/20/e3q8)', 'execution_filter: (sqlite3.OperationalError) no such table: cars\n[SQL: SELECT model FROM cars ORDER BY horsepower ASC LIMIT 1;]\n(Background on this error at: https://sqlalche.me/e/20/e3q8)', 'execution_filter: 5/5 candidates failed', 'execution_filter: no valid candidates after execution', "schema_validation_warning: unknown unqualified column 'model'; unknown unqualified column 'horsepower'", "schema_validation: unknown table 'car'"]

----------------------------------------------------------------------------------------------------
Q: Find the model of the car whose weight is below the average weight.
PRED: SELECT model FROM cars_data WHERE weight < (SELECT AVG(weight) FROM cars_data);
GOLD: SELECT T1.model FROM CAR_NAMES AS T1 JOIN CARS_DATA AS T2 ON T1.MakeId  =  T2.Id WHERE T2.Weight  <  (SELECT avg(Weight) FROM CARS_DATA)
EXEC: False ERR: (sqlite3.OperationalError) no such column: model
[SQL: SELECT model FROM car_makers WHERE weight < (SELECT AVG(weight) FROM car_makers);]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
WARNINGS: ['query_sketcher: failed to parse JSON response', 'query_sketcher: repaired malformed sketch with structured-output fallback', 'generator: using reduced ensemble budget for moderate complexity', 'execution_filter: (sqlite3.OperationalError) no such column: model\n[SQL: SELECT model FROM cars_data WHERE weight < (SELECT AVG(weight) FROM cars_data);]\n(Background on this error at: https://sqlalche.me/e/20/e3q8)', 'execution_filter: (sqlite3.OperationalError) no such column: model\n[SQL: SELECT model FROM cars_data WHERE weight < (SELECT AVG(weight) FROM cars_data);]\n(Background on this error at: https://sqlalche.me/e/20/e3q8)', 'execution_filter: 2/2 candidates failed', 'execution_filter: no valid candidates after execution', "schema_validation_warning: unknown unqualified column 'weight'; unknown unqualified column 'model'", "schema_validation_warning: unknown unqualified column 'weight'; unknown unqualified column 'model'", "schema_validation_warning: unknown unqualified column 'weight'; unknown unqualified column 'model'"]

----------------------------------------------------------------------------------------------------
Q: Find the name of the makers that produced some cars in the year of 1970?
PRED: SELECT DISTINCT Maker FROM car_makers;
GOLD: SELECT DISTINCT T1.Maker FROM CAR_MAKERS AS T1 JOIN MODEL_LIST AS T2 ON T1.Id  =  T2.Maker JOIN CAR_NAMES AS T3 ON T2.model  =  T3.model JOIN CARS_DATA AS T4 ON T3.MakeId  =  T4.id WHERE T4.year  =  '1970';
EXEC: False ERR: None
WARNINGS: ['execution_filter: (sqlite3.OperationalError) no such table: car_models\n[SQL: SELECT DISTINCT T1.Maker FROM car_makers AS T1 JOIN car_models AS T2 ON T1.Id = T2.Maker_Id WHERE T2.Year = 1970;]\n(Background on this error at: https://sqlalche.me/e/20/e3q8)', 'execution_filter: (sqlite3.OperationalError) no such table: car_models\n[SQL: SELECT DISTINCT T1.Maker FROM car_makers AS T1 JOIN car_models AS T2 ON T1.Id = T2.Maker_Id WHERE T2.Year = 1970;]\n(Background on this error at: https://sqlalche.me/e/20/e3q8)', 'execution_filter: (sqlite3.OperationalError) no such table: car_model\n[SQL: SELECT DISTINCT T1.Maker FROM car_makers AS T1 JOIN car_model AS T2 ON T1.Id = T2.maker_id WHERE T2.year = 1970;]\n(Background on this error at: https://sqlalche.me/e/20/e3q8)', 'execution_filter: 3/4 candidates failed', 'execution_filter: skipped judge for safe simple query with valid candidate']

----------------------------------------------------------------------------------------------------
Q: What is the name of the different car makers who produced a car in 1970?
PRED: SELECT DISTINCT Maker FROM car_makers;
GOLD: SELECT DISTINCT T1.Maker FROM CAR_MAKERS AS T1 JOIN MODEL_LIST AS T2 ON T1.Id  =  T2.Maker JOIN CAR_NAMES AS T3 ON T2.model  =  T3.model JOIN CARS_DATA AS T4 ON T3.MakeId  =  T4.id WHERE T4.year  =  '1970';
EXEC: False ERR: None
WARNINGS: ['query_sketcher: failed to parse JSON response', 'query_sketcher: repaired malformed sketch with structured-output fallback', 'execution_filter: (sqlite3.OperationalError) no such table: cars\n[SQL: SELECT DISTINCT T1.FullName FROM car_makers AS T1 JOIN cars AS T2 ON T1.Maker = T2.Maker WHERE T2.year = 1970;]\n(Background on this error at: https://sqlalche.me/e/20/e3q8)', 'execution_filter: (sqlite3.OperationalError) no such table: cars\n[SQL: SELECT DISTINCT T2.FullName FROM car_makers AS T1 JOIN cars AS T2 ON T1.Id = T2.maker_id WHERE T2.year = 1970;]\n(Background on this error at: https://sqlalche.me/e/20/e3q8)', 'execution_filter: (sqlite3.OperationalError) no such table: cars\n[SQL: SELECT DISTINCT T1.FullName FROM car_makers AS T1 JOIN cars AS T2 ON T1.Maker = T2.Maker WHERE T2.year = 1970;]\n(Background on this error at: https://sqlalche.me/e/20/e3q8)', 'execution_filter: 3/5 candidates failed', 'execution_filter: skipped judge for safe simple query with valid candidate']

----------------------------------------------------------------------------------------------------
Q: Find the make and production time of the cars that were produced in the earliest year?
PRED: SELECT Maker FROM car_makers;
GOLD: SELECT T2.Make ,  T1.Year FROM CARS_DATA AS T1 JOIN CAR_NAMES AS T2 ON T1.Id  =  T2.MakeId WHERE T1.Year  =  (SELECT min(YEAR) FROM CARS_DATA);
EXEC: False ERR: None
WARNINGS: ['query_sketcher: failed to parse JSON response', "query_sketcher: structured repair unavailable (Could not parse response content as the length limit was reached - CompletionUsage(completion_tokens=2032, prompt_tokens=226, total_tokens=2258, completion_tokens_details=CompletionTokensDetails(accepted_prediction_tokens=None, audio_tokens=0, reasoning_tokens=1587, rejected_prediction_tokens=None, image_tokens=0), prompt_tokens_details=PromptTokensDetails(audio_tokens=0, cached_tokens=0, cache_write_tokens=0, video_tokens=0), cost=0.0206025, is_byok=False, cost_details={'upstream_inference_cost': 0.0206025, 'upstream_inference_prompt_cost': 0.0002825, 'upstream_inference_completions_cost': 0.02032}))", 'query_sketcher: used deterministic fallback sketch', 'generator: using reduced ensemble budget for moderate complexity', 'execution_filter: (sqlite3.OperationalError) no such column: Production_time\n[SQL: SELECT Maker, Production_time FROM car_makers WHERE Production_time = (SELECT MIN(Production_time) FROM car_makers);]\n(Background on this error at: https://sqlalche.me/e/20/e3q8)', 'execution_filter: (sqlite3.OperationalError) no such column: production_time\n[SQL: SELECT Maker, production_time FROM car_makers WHERE production_year = (SELECT MIN(production_year) FROM car_makers);]\n(Background on this error at: https://sqlalche.me/e/20/e3q8)', 'execution_filter: 2/2 candidates failed', 'execution_filter: no valid candidates after execution', "schema_validation_warning: unknown unqualified column 'Production_time'"]

----------------------------------------------------------------------------------------------------
Q: What is the maker of the carr produced in the earliest year and what year was it?
PRED: SELECT Maker FROM car_makers LIMIT 1;
GOLD: SELECT T2.Make ,  T1.Year FROM CARS_DATA AS T1 JOIN CAR_NAMES AS T2 ON T1.Id  =  T2.MakeId WHERE T1.Year  =  (SELECT min(YEAR) FROM CARS_DATA);
EXEC: False ERR: None
WARNINGS: ['query_sketcher: failed to parse JSON response', "query_sketcher: structured repair unavailable (Could not parse response content as the length limit was reached - CompletionUsage(completion_tokens=2033, prompt_tokens=227, total_tokens=2260, completion_tokens_details=CompletionTokensDetails(accepted_prediction_tokens=None, audio_tokens=0, reasoning_tokens=1667, rejected_prediction_tokens=None, image_tokens=0), prompt_tokens_details=PromptTokensDetails(audio_tokens=0, cached_tokens=0, cache_write_tokens=0, video_tokens=0), cost=0.02061375, is_byok=False, cost_details={'upstream_inference_cost': 0.02061375, 'upstream_inference_prompt_cost': 0.00028375, 'upstream_inference_completions_cost': 0.02033}))", 'query_sketcher: used deterministic fallback sketch', 'generator: using reduced ensemble budget for moderate complexity', 'execution_filter: (sqlite3.OperationalError) no such column: Year\n[SQL: SELECT Maker, Year FROM car_makers ORDER BY Year ASC LIMIT 1;]\n(Background on this error at: https://sqlalche.me/e/20/e3q8)', 'execution_filter: (sqlite3.OperationalError) no such column: Year\n[SQL: SELECT Maker , Year FROM car_makers ORDER BY Year ASC LIMIT 1;]\n(Background on this error at: https://sqlalche.me/e/20/e3q8)', 'execution_filter: 2/2 candidates failed', 'execution_filter: no valid candidates after execution', "schema_validation_warning: unknown unqualified column 'Year'"]

----------------------------------------------------------------------------------------------------
Q: Which distinct car models are the produced after 1980?
PRED: SELECT DISTINCT Maker FROM car_makers WHERE Id IN (SELECT Id FROM car_makers WHERE Id > 0);
GOLD: SELECT DISTINCT T1.model FROM MODEL_LIST AS T1 JOIN CAR_NAMES AS T2 ON T1.model  =  T2.model JOIN CARS_DATA AS T3 ON T2.MakeId  =  T3.id WHERE T3.year  >  1980;
EXEC: False ERR: None
WARNINGS: ['query_sketcher: failed to parse JSON response', 'query_sketcher: repaired malformed sketch with structured-output fallback', 'execution_filter: (sqlite3.OperationalError) no such table: models\n[SQL: SELECT DISTINCT model FROM models WHERE year > 1980;]\n(Background on this error at: https://sqlalche.me/e/20/e3q8)', 'execution_filter: (sqlite3.OperationalError) no such table: models\n[SQL: SELECT DISTINCT model FROM models WHERE year > 1980;]\n(Background on this error at: https://sqlalche.me/e/20/e3q8)', 'execution_filter: (sqlite3.OperationalError) no such table: models\n[SQL: SELECT DISTINCT model FROM models WHERE year > 1980;]\n(Background on this error at: https://sqlalche.me/e/20/e3q8)', 'execution_filter: 3/3 candidates failed', 'execution_filter: no valid candidates after execution', "schema_validation_warning: unknown unqualified column 'model'; unknown unqualified column 'year'", "schema_validation: unknown table 'models'"]

----------------------------------------------------------------------------------------------------
Q: How many car models are produced by each maker? List the count and the maker full name.
PRED: SELECT count(*), FullName FROM car_makers GROUP BY FullName;
GOLD: SELECT Count(*) ,  T2.FullName ,  T2.id FROM MODEL_LIST AS T1 JOIN CAR_MAKERS AS T2 ON T1.Maker  =  T2.Id GROUP BY T2.id;
EXEC: False ERR: None
WARNINGS: ['selector: padded reranker selection with vector candidates', 'query_sketcher: failed to parse JSON response', "query_sketcher: structured repair unavailable (Could not parse response content as the length limit was reached - CompletionUsage(completion_tokens=2013, prompt_tokens=230, total_tokens=2243, completion_tokens_details=CompletionTokensDetails(accepted_prediction_tokens=None, audio_tokens=0, reasoning_tokens=2013, rejected_prediction_tokens=None, image_tokens=0), prompt_tokens_details=PromptTokensDetails(audio_tokens=0, cached_tokens=203, cache_write_tokens=0, video_tokens=0), cost=0.020189125, is_byok=False, cost_details={'upstream_inference_cost': 0.020189125, 'upstream_inference_prompt_cost': 5.9125e-05, 'upstream_inference_completions_cost': 0.02013}))", 'query_sketcher: used deterministic fallback sketch', 'generator: using reduced ensemble budget for moderate complexity']

----------------------------------------------------------------------------------------------------
Q: What is the number of car models that are produced by each maker and what is the id and full name of each maker?
PRED: SELECT count(*), Id, FullName FROM car_makers GROUP BY Id;
GOLD: SELECT Count(*) ,  T2.FullName ,  T2.id FROM MODEL_LIST AS T1 JOIN CAR_MAKERS AS T2 ON T1.Maker  =  T2.Id GROUP BY T2.id;
EXEC: False ERR: None
WARNINGS: ['selector: padded reranker selection with vector candidates', 'query_sketcher: failed to parse JSON response', "query_sketcher: structured repair unavailable (Could not parse response content as the length limit was reached - CompletionUsage(completion_tokens=2032, prompt_tokens=235, total_tokens=2267, completion_tokens_details=CompletionTokensDetails(accepted_prediction_tokens=None, audio_tokens=0, reasoning_tokens=1964, rejected_prediction_tokens=None, image_tokens=0), prompt_tokens_details=PromptTokensDetails(audio_tokens=0, cached_tokens=0, cache_write_tokens=0, video_tokens=0), cost=0.02061375, is_byok=False, cost_details={'upstream_inference_cost': 0.02061375, 'upstream_inference_prompt_cost': 0.00029375, 'upstream_inference_completions_cost': 0.02032}))", 'query_sketcher: used deterministic fallback sketch', 'generator: using reduced ensemble budget for moderate complexity']

----------------------------------------------------------------------------------------------------
Q: What is the accelerate of the car make amc hornet sportabout (sw)?
PRED: SELECT 'Unanswerable: required column or table missing from schema.';
GOLD: SELECT T1.Accelerate FROM CARS_DATA AS T1 JOIN CAR_NAMES AS T2 ON T1.Id  =  T2.MakeId WHERE T2.Make  =  'amc hornet sportabout (sw)';
EXEC: False ERR: None
WARNINGS: ['execution_filter: (sqlite3.OperationalError) near "I": syntax error\n[SQL: I cannot generate the SQL because the required column `accelerate` and the table containing car model details are not present in the provided schema.;]\n(Background on this error at: https://sqlalche.me/e/20/e3q8)', "execution_filter: (sqlite3.OperationalError) no such column: accelerate\n[SQL: SELECT accelerate FROM car_makers WHERE Maker = 'amc hornet sportabout (sw)';]\n(Background on this error at: https://sqlalche.me/e/20/e3q8)", "execution_filter: (sqlite3.OperationalError) no such column: accelerate\n[SQL: SELECT accelerate FROM car_makers WHERE Maker = 'amc hornet sportabout (sw)';]\n(Background on this error at: https://sqlalche.me/e/20/e3q8)", 'execution_filter: 3/3 candidates failed', 'execution_filter: no valid candidates after execution', 'schema_validation: parse error: Invalid expression / Unexpected token. Line 1, Col: 17.\n  I cannot \x1b[4mgenerate\x1b[0m the SQL because the required column `accelerate` and the table containing car model details are not']

----------------------------------------------------------------------------------------------------
Q: How much does the car accelerate that makes amc hornet sportabout (sw)?
PRED: SELECT * FROM car_makers WHERE Maker = 'amc';
GOLD: SELECT T1.Accelerate FROM CARS_DATA AS T1 JOIN CAR_NAMES AS T2 ON T1.Id  =  T2.MakeId WHERE T2.Make  =  'amc hornet sportabout (sw)';
EXEC: False ERR: None
WARNINGS: ['execution_filter: skipped judge for safe simple query with valid candidate']

----------------------------------------------------------------------------------------------------
Q: How many car models are produced in the usa?
PRED: SELECT COUNT(car_makers.Id) FROM car_makers JOIN countries ON car_makers.Country = countries.CountryId WHERE countries.CountryName = 'usa';
GOLD: SELECT count(*) FROM MODEL_LIST AS T1 JOIN CAR_MAKERS AS T2 ON T1.Maker  =  T2.Id JOIN COUNTRIES AS T3 ON T2.Country  =  T3.CountryId WHERE T3.CountryName  =  'usa';
EXEC: False ERR: None
WARNINGS: []

----------------------------------------------------------------------------------------------------
Q: What is the count of the car models produced in the United States?